# Tomcat
server:
  port: 8714



#EUREKA配置
eureka:
  client:
    service-url:
      defaultZone: http://11.11.12.3:8601/eureka/


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//192.168.1.34:1521/db
    username: MOBAOPAY_AUDIT
    password: audit#8799#pay2uat
#    password: LogWDV+eq42qwsXhF1gX1ljVPxubJnXdOOujSwJ/d8uUi8WgpedDCnp8ajx2qsCd7DMCpyoOR3l+Kl8SSOKneg==
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      # 打开PSCache，并且指定每个连接上 Cache的大小
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
#      filter:
#        config:
#          enabled: true
#      connection-properties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIZ2Kw49+LzW39Gz7+g4XAH9xTh7smAH1PPKH8UfT51CPFhCbPEINRaps4IJw03lRsUFVmG6zasaoUosg9RJNqsCAwEAAQ==
#  redis:
#    database: 4
#    password: mobo_cloud
#    timeout: 6000
#    cluster:
#      nodes: 10.2.3.7:6381, 10.2.3.8:6381
#    pool:
#      max-active: 8
#      min-idle: 0
#      max-wait: -1
  kafka:
    bootstrap-servers: 11.11.12.8:9092, 11.11.12.9:9092, 11.11.12.10:9092
    #消费者的配置
    consumer:
      group-id: zb_cloud


tx-lcn:
  client:
    manager-address: 11.11.12.36:8070, 11.11.12.37:8070
    resource-order: 0
  logger:
    enabled: false
  message:
    netty:
      wait-time: 5000
  springcloud:
    loadbalance:
      enabled: true

#mybatis-plus:
#  configuration:
#    # 打印sql语句(包含查询结果集)
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#自定义配置
#定时任务执行IP
dbc.taskIp: 11.11.12.28
#运行环境
dbc.env: ${spring.profiles.active}
