# Tomcat
server:
  port: 7007



#EUREKA配置
eureka:
  client:
    service-url:
      defaultZone: http://10.2.3.1:8601/eureka/


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//10.2.4.1:1521/orcl
    username: MOBAOPAY_AUDIT
    password: audit#6654#pay2zb
#    password: l9cpKE4siR96Uf9LJcBt4BvOwda2HNUdE7VdQKqa3Rx8Uq0Z/2uKKCoJXa0aGCOh6KIjE0bOuPOOuYWWQjvVWw==
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      # 打开PSCache，并且指定每个连接上 Cache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
#      filter:
#        config:
#          enabled: true
#      connection-properties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALgqC9QJ8OgahvetbDnDP4k9G16mLnD/mL5m8VMlrHVjOMh33cqr5dh9oKH/ENtfLZdwoPhgI6NZrBedawDc2uMCAwEAAQ==
#  redis:
#    database: 4
#    password: mobo_cloud
#    timeout: 6000
#    cluster:
#      nodes: 10.2.3.7:6381, 10.2.3.8:6381
#    pool:
#      max-active: 8
#      min-idle: 0
#      max-wait: -1
  kafka:
    bootstrap-servers: 10.2.3.6:9092, 10.2.3.7:9092, 10.2.3.8:9092
    #消费者的配置
    consumer:
      group-id: mobo_kafka


tx-lcn:
  client:
    manager-address: 10.2.3.1:8070, 10.2.3.3:8070
    resource-order: 0
  logger:
    enabled: false
  message:
    netty:
      wait-time: 5000
  springcloud:
    loadbalance:
      enabled: true

#mybatis-plus:
#  configuration:
#    # 打印sql语句(包含查询结果集)
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#自定义配置
#定时任务执行IP
dbc.taskIp: 10.2.3.25
#运行环境
dbc.env: ${spring.profiles.active}
