--联行号表
CREATE TABLE "BAS_UNION_BANK_NUMBER" (
"ID" NUMBER(16) NOT NULL ,
"UNION_BANK_NO" VARCHAR2(15 BYTE) NULL ,
"HEAD_UNION_BANK_NO" VARCHAR2(15 BYTE) NULL ,
"AREA_CODE" CHAR(4 BYTE) NULL ,
"UNION_BANK_NAME" VARCHAR2(150 BYTE) NULL ,
"BANK_NO" CHAR(3 BYTE) NULL ,
"BANK_NAME" VARCHAR2(150 BYTE) NULL 
);
COMMENT ON TABLE "BAS_UNION_BANK_NUMBER" IS '联行号表';
COMMENT ON COLUMN "BAS_UNION_BANK_NUMBER"."UNION_BANK_NO" IS '联行号';
COMMENT ON COLUMN "BAS_UNION_BANK_NUMBER"."HEAD_UNION_BANK_NO" IS '总行联行号';
COMMENT ON COLUMN "BAS_UNION_BANK_NUMBER"."AREA_CODE" IS '地区代码';
COMMENT ON COLUMN "BAS_UNION_BANK_NUMBER"."UNION_BANK_NAME" IS '银行名称';
ALTER TABLE "BAS_UNION_BANK_NUMBER" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "BAS_UNION_BANK_NUMBER" ADD PRIMARY KEY ("ID");

--联行地区表
CREATE TABLE "BAS_UNION_BANK_AREA_CODE" (
"ID" NUMBER(16) NOT NULL ,
"PROVINCE" VARCHAR2(100 BYTE) NULL ,
"PROVINCE_CODE" CHAR(4 BYTE) NULL ,
"CITY" VARCHAR2(100 BYTE) NULL ,
"CITY_CODE" CHAR(4 BYTE) NULL
);
ALTER TABLE "BAS_UNION_BANK_AREA_CODE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "BAS_UNION_BANK_AREA_CODE" ADD PRIMARY KEY ("ID");

--MCC编码表
CREATE TABLE "BAS_MCC" (
"ID" NUMBER(16) NOT NULL ,
"MCC_CODE" VARCHAR2(10) NULL ,
"KIND_CODE" VARCHAR2(20) NULL ,
"FIRST_KIND" VARCHAR2(50) NULL ,
"SECOND_KIND" VARCHAR2(50) NULL ,
"THIRD_KIND" VARCHAR2(100) NULL 
);
ALTER TABLE "BAS_MCC" ADD PRIMARY KEY ("ID");

--微信业务种类表
CREATE TABLE "BAS_WECHAT_BUSINESS_KIND" (
"ID" NUMBER(16) NOT NULL ,
"KIND_CODE" VARCHAR2(10) NULL ,
"FIRST_KIND" VARCHAR2(30) NULL ,
"SECOND_KIND" VARCHAR2(30) NULL ,
"THIRD_KIND" VARCHAR2(100) NULL 
);
ALTER TABLE "BAS_WECHAT_BUSINESS_KIND" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "BAS_WECHAT_BUSINESS_KIND" ADD PRIMARY KEY ("ID");

--网联业务种类表
CREATE TABLE "BAS_NUCC_BUSINESS_KIND" (
"ID" NUMBER(16) NOT NULL ,
"CODE" VARCHAR2(10) NULL ,
"NAME" VARCHAR2(100) NULL ,
"PARENT_CODE" VARCHAR2(10) NULL 
);
ALTER TABLE "BAS_NUCC_BUSINESS_KIND" ADD PRIMARY KEY ("ID");

--行业信息表
CREATE TABLE "BAS_INDUSTRY_INFO" (
"ID" NUMBER(16) NOT NULL ,
"PARENT_CODE" VARCHAR2(10 BYTE) NULL ,
"CODE" VARCHAR2(10 BYTE) NULL ,
"NAME" VARCHAR2(100 BYTE) NULL 
);
ALTER TABLE "BAS_INDUSTRY_INFO" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "BAS_INDUSTRY_INFO" ADD PRIMARY KEY ("ID");

--审核事件类型表
CREATE TABLE "AUDIT_EVENT_TYPE" (
"ID" NUMBER(16) NOT NULL ,
"AUDIT_MODULE" CHAR(2 BYTE) NULL ,
"AUDIT_EVENT_TYPE" CHAR(2 BYTE) NULL ,
"APPLICATION" VARCHAR2(255 BYTE) NULL 
);
COMMENT ON COLUMN "AUDIT_EVENT_TYPE"."AUDIT_MODULE" IS '审核模块 （数据字典：audit_module）';
COMMENT ON COLUMN "AUDIT_EVENT_TYPE"."AUDIT_EVENT_TYPE" IS '审核事件类型（数据字典：audit_event_type）';
COMMENT ON COLUMN "AUDIT_EVENT_TYPE"."APPLICATION" IS '用途';
ALTER TABLE "AUDIT_EVENT_TYPE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "AUDIT_EVENT_TYPE" ADD PRIMARY KEY ("ID");

--审核流程表
CREATE SEQUENCE  "SEQ_AUDIT_EVENT_FLOW"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20 NOORDER  NOCYCLE;
CREATE TABLE "AUDIT_EVENT_FLOW" (
"ID" NUMBER(16) NOT NULL ,
"AUDIT_EVENT_TYPE" CHAR(2 BYTE) NULL ,
"NODE_CODE" VARCHAR2(4 BYTE) NULL ,
"NODE_NAME" VARCHAR2(60 BYTE) NULL ,
"OPERATOR_ROLE" VARCHAR2(100 BYTE) NULL ,
"OPERATOR_PERMISSION" VARCHAR2(100 BYTE) NULL ,
"IF_EDIT" CHAR(1 BYTE) NULL ,
"ROLE_NAME" VARCHAR2(200 BYTE) NULL ,
"BUTTON_PERMISSION" VARCHAR2(100 BYTE) NULL 
);
COMMENT ON COLUMN "AUDIT_EVENT_FLOW"."AUDIT_EVENT_TYPE" IS '审核事件类型（数据字典：audit_event_type）';
COMMENT ON COLUMN "AUDIT_EVENT_FLOW"."NODE_CODE" IS '节点编码';
COMMENT ON COLUMN "AUDIT_EVENT_FLOW"."NODE_NAME" IS '节点名称';
COMMENT ON COLUMN "AUDIT_EVENT_FLOW"."OPERATOR_ROLE" IS '操作角色';
COMMENT ON COLUMN "AUDIT_EVENT_FLOW"."OPERATOR_PERMISSION" IS '操作权限';
COMMENT ON COLUMN "AUDIT_EVENT_FLOW"."IF_EDIT" IS '是否可修改 1-是，0-否';
COMMENT ON COLUMN "AUDIT_EVENT_FLOW"."ROLE_NAME" IS '角色名称';
COMMENT ON COLUMN "AUDIT_EVENT_FLOW"."BUTTON_PERMISSION" IS '按钮权限';
ALTER TABLE "AUDIT_EVENT_FLOW" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "AUDIT_EVENT_FLOW" ADD PRIMARY KEY ("ID");

--数据字典类型表
CREATE TABLE "BAS_DICTIONARY_TYPE" (
"ID" NUMBER(16) NOT NULL ,
"CODE" VARCHAR2(50 BYTE) NULL ,
"NAME" VARCHAR2(60 BYTE) NULL ,
"REMARK" VARCHAR2(255 BYTE) NULL ,
"IF_EDIT" CHAR(1 BYTE) NULL 
);
COMMENT ON COLUMN "BAS_DICTIONARY_TYPE"."IF_EDIT" IS '是否可修改 1-是';
ALTER TABLE "BAS_DICTIONARY_TYPE" ADD UNIQUE ("CODE");
ALTER TABLE "BAS_DICTIONARY_TYPE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "BAS_DICTIONARY_TYPE" ADD PRIMARY KEY ("ID");

--数据字典表
CREATE TABLE "BAS_DICTIONARY" (
"ID" NUMBER(16) NOT NULL ,
"DIC_TYPE_ID" NUMBER NOT NULL ,
"VALUE" VARCHAR2(30 BYTE) NULL ,
"NAME" VARCHAR2(50 BYTE) NULL ,
"REMARK" VARCHAR2(255 BYTE) NULL ,
"IF_EDIT" CHAR(1 BYTE) NULL 
);
COMMENT ON COLUMN "BAS_DICTIONARY"."IF_EDIT" IS '是否可修改 1-是';
ALTER TABLE "BAS_DICTIONARY" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "BAS_DICTIONARY" ADD CHECK ("DIC_TYPE_ID" IS NOT NULL);
ALTER TABLE "BAS_DICTIONARY" ADD PRIMARY KEY ("ID");

--银行编码表
CREATE SEQUENCE  "SEQ_BAS_BANK_CODE"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20 NOORDER  NOCYCLE;
CREATE TABLE "BAS_BANK_CODE" (
"ID" NUMBER(16) NOT NULL ,
"BANK_CODE" VARCHAR2(10 BYTE) NULL ,
"BANK_NAME" VARCHAR2(150 BYTE) NULL ,
"HEAD_UNION_BANK_NO" VARCHAR2(30 BYTE) NULL ,
"INTERNET_BANK_DEBIT" CHAR(1 BYTE) NULL ,
"INTERNET_BANK_CREDIT" CHAR(1 BYTE) NULL ,
"INTERNET_BANK_MIX" CHAR(1 BYTE) NULL ,
"ENTERPRISE_INTERNET_BANK" CHAR(1 BYTE) NULL ,
"WITHDRAW_CASH" CHAR(1 BYTE) NULL ,
"ENTRUST_PAY" CHAR(1 BYTE) NULL ,
"AGREEMENT_DEBIT" CHAR(1 BYTE) NULL ,
"AGREEMENT_CREDIT" CHAR(1 BYTE) NULL ,
"QUICK_DEBIT" CHAR(1 BYTE) NULL ,
"QUICK_CREDIT" CHAR(1 BYTE) NULL 
);
COMMENT ON TABLE "BAS_BANK_CODE" IS '银行编码表';
COMMENT ON COLUMN "BAS_BANK_CODE"."BANK_CODE" IS '银行编码';
COMMENT ON COLUMN "BAS_BANK_CODE"."BANK_NAME" IS '发卡行名称';
COMMENT ON COLUMN "BAS_BANK_CODE"."HEAD_UNION_BANK_NO" IS '总行联行号';
COMMENT ON COLUMN "BAS_BANK_CODE"."INTERNET_BANK_DEBIT" IS '网银借记卡（1-启用，0-禁用）';
COMMENT ON COLUMN "BAS_BANK_CODE"."INTERNET_BANK_CREDIT" IS '网银贷记卡（1-启用，0-禁用）';
COMMENT ON COLUMN "BAS_BANK_CODE"."INTERNET_BANK_MIX" IS '网银混合（1-启用，0-禁用）';
COMMENT ON COLUMN "BAS_BANK_CODE"."ENTERPRISE_INTERNET_BANK" IS '支持企业网银（1-启用，0-禁用）';
COMMENT ON COLUMN "BAS_BANK_CODE"."WITHDRAW_CASH" IS '提现（1-启用，0-禁用）';
COMMENT ON COLUMN "BAS_BANK_CODE"."ENTRUST_PAY" IS '委托付款（1-启用，0-禁用）';
COMMENT ON COLUMN "BAS_BANK_CODE"."AGREEMENT_DEBIT" IS '协议支付借记卡（1-启用，0-禁用）';
COMMENT ON COLUMN "BAS_BANK_CODE"."AGREEMENT_CREDIT" IS '协议支付贷记卡（1-启用，0-禁用）';
COMMENT ON COLUMN "BAS_BANK_CODE"."QUICK_DEBIT" IS '快捷支付借记卡（1-启用，0-禁用）';
COMMENT ON COLUMN "BAS_BANK_CODE"."QUICK_CREDIT" IS '快捷支付贷记卡（1-启用，0-禁用）';
ALTER TABLE "BAS_BANK_CODE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "BAS_BANK_CODE" ADD PRIMARY KEY ("ID");


--代理基本信息（审核）
CREATE SEQUENCE  "SEQ_AUDIT_AGENT_BASIC_INFO"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE TABLE "AUDIT_AGENT_BASIC_INFO" (
"ID" NUMBER(16) NOT NULL ,
"AUDIT_EVENT_ID" NUMBER(16) NULL ,
"NAME" VARCHAR2(50 BYTE) NULL ,
"SHORT_NAME" VARCHAR2(15 BYTE) NULL ,
"LEGAL_PERSON" VARCHAR2(40 BYTE) NULL ,
"LEGAL_PERSON_NATIONALITY" VARCHAR2(20 BYTE) NULL ,
"LEGAL_PERSON_CERT_TYPE" CHAR(1 BYTE) NULL ,
"LEGAL_PERSON_CERT_NUM" VARCHAR2(50 BYTE) NULL ,
"LEGAL_PERSON_CERT_PERIOD_START" CHAR(10 BYTE) NULL ,
"LEGAL_PERSON_CERT_PERIOD_END" CHAR(10 BYTE) NULL ,
"BUSINESS_LICENCE_NO" VARCHAR2(30 BYTE) NULL ,
"BUSINESS_LICENCE_PERIOD_START" CHAR(10 BYTE) NULL ,
"BUSINESS_LICENCE_PERIOD_END" CHAR(10 BYTE) NULL ,
"REGISTERED_FUND" VARCHAR2(20 BYTE) NULL ,
"BUSINESS_SCOPE" VARCHAR2(3000 BYTE) NULL ,
"AGENT_ADDRESS" VARCHAR2(400 BYTE) NULL ,
"AGENT_PLATFORM_URL" VARCHAR2(150 BYTE) NULL ,
"CONTACT_PERSON" VARCHAR2(30 BYTE) NULL ,
"CONTACT_PHONE" VARCHAR2(20 BYTE) NULL ,
"CREATE_TIME" CHAR(19 BYTE) NULL ,
"UPDATE_TIME" CHAR(19 BYTE) NULL ,
"UPDATE_RECORD" VARCHAR2(4000 BYTE) NULL ,
"AGENT_NO" VARCHAR2(20 BYTE) NULL ,
"CONTACT_CERT_NUM" VARCHAR2(50 BYTE) NULL ,
"CONTACT_ID_PERIOD_START" CHAR(10 BYTE) NULL ,
"CONTACT_ID_PERIOD_END" CHAR(10 BYTE) NULL ,
"AGENT_STATUS" CHAR(1 BYTE) NULL ,
"BRANCH_NO" CHAR(3 BYTE) NULL ,
"FORMAL_ID" NUMBER(16) NULL 
);
COMMENT ON COLUMN "AUDIT_AGENT_BASIC_INFO"."AUDIT_EVENT_ID" IS '审核事件id';
COMMENT ON COLUMN "AUDIT_AGENT_BASIC_INFO"."NAME" IS '代理商全称';
COMMENT ON COLUMN "AUDIT_AGENT_BASIC_INFO"."SHORT_NAME" IS '代理商简称';
COMMENT ON COLUMN "AUDIT_AGENT_BASIC_INFO"."LEGAL_PERSON" IS '法人代表';
COMMENT ON COLUMN "AUDIT_AGENT_BASIC_INFO"."LEGAL_PERSON_NATIONALITY" IS '法人国籍（数据字典 nationality）';
COMMENT ON COLUMN "AUDIT_AGENT_BASIC_INFO"."LEGAL_PERSON_CERT_TYPE" IS '法人证件类型（数据字典 certificate_type：0-身份证 1-护照）';
COMMENT ON COLUMN "AUDIT_AGENT_BASIC_INFO"."LEGAL_PERSON_CERT_NUM" IS '法人证件号';
COMMENT ON COLUMN "AUDIT_AGENT_BASIC_INFO"."LEGAL_PERSON_CERT_PERIOD_START" IS '法人证件有效期开始时间';
COMMENT ON COLUMN "AUDIT_AGENT_BASIC_INFO"."LEGAL_PERSON_CERT_PERIOD_END" IS '法人证件有效期结束时间';
COMMENT ON COLUMN "AUDIT_AGENT_BASIC_INFO"."BUSINESS_LICENCE_NO" IS '营业执照号';
COMMENT ON COLUMN "AUDIT_AGENT_BASIC_INFO"."BUSINESS_LICENCE_PERIOD_START" IS '营业执照有效期开始时间';
COMMENT ON COLUMN "AUDIT_AGENT_BASIC_INFO"."BUSINESS_LICENCE_PERIOD_END" IS '营业执照有效期结束时间';
COMMENT ON COLUMN "AUDIT_AGENT_BASIC_INFO"."REGISTERED_FUND" IS '注册资金';
COMMENT ON COLUMN "AUDIT_AGENT_BASIC_INFO"."BUSINESS_SCOPE" IS '企业经营范围';
COMMENT ON COLUMN "AUDIT_AGENT_BASIC_INFO"."AGENT_ADDRESS" IS '代理商地址';
COMMENT ON COLUMN "AUDIT_AGENT_BASIC_INFO"."AGENT_PLATFORM_URL" IS '代理平台网址';
COMMENT ON COLUMN "AUDIT_AGENT_BASIC_INFO"."CONTACT_PERSON" IS '联系人';
COMMENT ON COLUMN "AUDIT_AGENT_BASIC_INFO"."CONTACT_PHONE" IS '联系电话';
COMMENT ON COLUMN "AUDIT_AGENT_BASIC_INFO"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "AUDIT_AGENT_BASIC_INFO"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "AUDIT_AGENT_BASIC_INFO"."UPDATE_RECORD" IS '更新记录';
COMMENT ON COLUMN "AUDIT_AGENT_BASIC_INFO"."AGENT_NO" IS '代理商号';
COMMENT ON COLUMN "AUDIT_AGENT_BASIC_INFO"."CONTACT_CERT_NUM" IS '联系人身份证号码';
COMMENT ON COLUMN "AUDIT_AGENT_BASIC_INFO"."CONTACT_ID_PERIOD_START" IS '联系人身份证有效期开始时间';
COMMENT ON COLUMN "AUDIT_AGENT_BASIC_INFO"."CONTACT_ID_PERIOD_END" IS '联系人身份证有效期结束时间';
COMMENT ON COLUMN "AUDIT_AGENT_BASIC_INFO"."AGENT_STATUS" IS '代理状态';
COMMENT ON COLUMN "AUDIT_AGENT_BASIC_INFO"."BRANCH_NO" IS '分支机构号';
COMMENT ON COLUMN "AUDIT_AGENT_BASIC_INFO"."FORMAL_ID" IS '对应已审核通过正式数据的ID';
ALTER TABLE "AUDIT_AGENT_BASIC_INFO" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "AUDIT_AGENT_BASIC_INFO" ADD PRIMARY KEY ("ID");


--审核事件
CREATE SEQUENCE  "SEQ_AUDIT_EVENT"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE TABLE "AUDIT_EVENT" (
"ID" NUMBER(16) NOT NULL ,
"AUDIT_MODULE" CHAR(2 BYTE) NULL ,
"AUDIT_EVENT_TYPE" CHAR(2 BYTE) NULL ,
"SUBJECT" VARCHAR2(90 BYTE) NULL ,
"NODE_CODE" CHAR(4 BYTE) NULL ,
"STATUS" CHAR(2 BYTE) NULL ,
"CREATE_TIME" CHAR(19 BYTE) NULL ,
"UPDATE_TIME" CHAR(19 BYTE) NULL ,
"SUBJECT_CODE" VARCHAR2(30 BYTE) NULL 
);
COMMENT ON COLUMN "AUDIT_EVENT"."AUDIT_MODULE" IS '审核模块 （数据字典：audit_module）';
COMMENT ON COLUMN "AUDIT_EVENT"."AUDIT_EVENT_TYPE" IS '审核事件类型（数据字典：audit_event_type）';
COMMENT ON COLUMN "AUDIT_EVENT"."SUBJECT" IS '审核主体';
COMMENT ON COLUMN "AUDIT_EVENT"."NODE_CODE" IS '节点编码';
COMMENT ON COLUMN "AUDIT_EVENT"."STATUS" IS '事件状态';
COMMENT ON COLUMN "AUDIT_EVENT"."SUBJECT_CODE" IS '审核主体在业务关系中的唯一标识（客户号、......）';
ALTER TABLE "AUDIT_EVENT" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "AUDIT_EVENT" ADD PRIMARY KEY ("ID");


--审核事件明细
CREATE SEQUENCE  "SEQ_AUDIT_EVENT_DETAIL"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE TABLE "AUDIT_EVENT_DETAIL" (
"ID" NUMBER(16) NOT NULL ,
"AUDIT_EVENT_ID" NUMBER(16) NULL ,
"OPERATION" CHAR(2 BYTE) NULL ,
"DESCRIPTION" VARCHAR2(3000 BYTE) NULL ,
"CREATE_TIME" CHAR(19 BYTE) NULL ,
"NODE_NAME" VARCHAR2(60 BYTE) NULL ,
"OPERATOR" VARCHAR2(30 BYTE) NULL ,
"UPDATE_RECORD" VARCHAR2(4000) NULL ,
"NODE_CODE" CHAR(4 BYTE) NULL ,
"IF_LOG" CHAR(1 BYTE) NULL 
);
COMMENT ON COLUMN "AUDIT_EVENT_DETAIL"."AUDIT_EVENT_ID" IS '审核事件ID';
COMMENT ON COLUMN "AUDIT_EVENT_DETAIL"."OPERATION" IS '操作';
COMMENT ON COLUMN "AUDIT_EVENT_DETAIL"."DESCRIPTION" IS '描述';
COMMENT ON COLUMN "AUDIT_EVENT_DETAIL"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "AUDIT_EVENT_DETAIL"."NODE_NAME" IS '节点名称';
COMMENT ON COLUMN "AUDIT_EVENT_DETAIL"."OPERATOR" IS '操作人员';
COMMENT ON COLUMN "AUDIT_EVENT_DETAIL"."UPDATE_RECORD" IS '修改记录';
COMMENT ON COLUMN "AUDIT_EVENT_DETAIL"."NODE_CODE" IS '节点代码';
COMMENT ON COLUMN "AUDIT_EVENT_DETAIL"."IF_LOG" IS '是否为日志(如在“提交审核”前，会有新增和多次修改，都会形成一条记录存于此表中。这些是每一步的日志记录，并非审核记录。)';
ALTER TABLE "AUDIT_EVENT_DETAIL" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "AUDIT_EVENT_DETAIL" ADD PRIMARY KEY ("ID");


--商户中心账号（审核）
CREATE SEQUENCE  "SEQ_A_M_C_A"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE TABLE "AUDIT_MERCHANT_CENTRE_ACCOUNT" (
"ID" NUMBER(16) NOT NULL ,
"AUDIT_EVENT_ID" NUMBER(16) NULL ,
"CUSTOMER_NO" VARCHAR2(20 BYTE) NULL ,
"MANAGER_EMAIL" VARCHAR2(50 BYTE) NULL ,
"MANAGER_TEL" VARCHAR2(20 BYTE) NULL ,
"CREATE_TIME" CHAR(19 BYTE) NULL ,
"UPDATE_TIME" CHAR(19 BYTE) NULL ,
"UPDATE_RECORD" VARCHAR2(4000 BYTE) NULL 
);
COMMENT ON COLUMN "AUDIT_MERCHANT_CENTRE_ACCOUNT"."MANAGER_EMAIL" IS '商户管理员邮箱';
COMMENT ON COLUMN "AUDIT_MERCHANT_CENTRE_ACCOUNT"."MANAGER_TEL" IS '商户管理员绑定手机';
COMMENT ON COLUMN "AUDIT_MERCHANT_CENTRE_ACCOUNT"."UPDATE_RECORD" IS '修改记录';
ALTER TABLE "AUDIT_MERCHANT_CENTRE_ACCOUNT" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "AUDIT_MERCHANT_CENTRE_ACCOUNT" ADD PRIMARY KEY ("ID");


--商户配置（审核）
CREATE SEQUENCE  "SEQ_AUDIT_M_CONFIG"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE TABLE "AUDIT_MERCHANT_CONFIG" (
"ID" NUMBER(16) NOT NULL ,
"AUDIT_EVENT_ID" NUMBER(16) NULL ,
"CUSTOMER_NO" VARCHAR2(20 BYTE) NULL ,
"SETTLEMENT_PERIOD" VARCHAR2(10 BYTE) NULL ,
"CONSUME" CHAR(1 BYTE) NULL ,
"REFUND" CHAR(1 BYTE) NULL ,
"SETTLEMENT" CHAR(1 BYTE) NULL ,
"CROSS_BORDER" CHAR(1 BYTE) NULL ,
"PAY_TYPE" VARCHAR2(150 BYTE) NULL ,
"PAY_TYPE_DIC" VARCHAR2(1000 BYTE) NULL,
"MIN_WITHDRAW_CASH_MONEY" VARCHAR2(20 BYTE) NULL ,
"PAYMENT_ACCOUNT" CHAR(1 BYTE) NULL ,
"EXCHANGE_DEPOSIT_RATE" VARCHAR2(10 BYTE) NULL ,
"PURCHASE_PAYMENT_BANK_CHANNEL" VARCHAR2(5 BYTE) NULL ,
"RECEIVE_SETT_BANK_CHANNEL" VARCHAR2(5 BYTE) NULL ,
"OPENED_CURRENCY_ACCOUNT" VARCHAR2(150 BYTE) NULL ,
"OPENED_CURRENCY_ACCOUNT_DIC" VARCHAR2(1000 BYTE) NULL ,
"CREATE_TIME" CHAR(19 BYTE) NULL ,
"UPDATE_TIME" CHAR(19 BYTE) NULL ,
"UPDATE_RECORD" VARCHAR2(4000 BYTE) NULL
);
ALTER TABLE "AUDIT_MERCHANT_CONFIG" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "AUDIT_MERCHANT_CONFIG" ADD PRIMARY KEY ("ID");


--电子资料（审核）
CREATE SEQUENCE  "SEQ_AUDIT_M_E_D"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE TABLE "AUDIT_MERCHANT_ELECTRONIC_DATA" (
"ID" NUMBER(16) NOT NULL ,
"BUSINESS_LICENSE" VARCHAR2(1000 BYTE) NULL ,
"OPEN_ACCOUNT_PERMIT" VARCHAR2(1000 BYTE) NULL ,
"CORP_ID_CARD_FRONT" VARCHAR2(1000 BYTE) NULL ,
"CORP_ID_CARD_BACK" VARCHAR2(1000 BYTE) NULL ,
"CORP_IDENTITY_CHECK" VARCHAR2(1000 BYTE) NULL ,
"CORP_HAND_ID_CARD" VARCHAR2(1000 BYTE) NULL ,
"ICP_ARCHIVAL" VARCHAR2(1000 BYTE) NULL ,
"ICP_AUTHORIZATION" VARCHAR2(1000 BYTE) NULL ,
"MOBAO_PAYMENT_AGREEMENT" VARCHAR2(1000 BYTE) NULL ,
"MOBAO_MERCHANT_REGISTRATION" VARCHAR2(1000 BYTE) NULL ,
"MOBAO_ENTRUST_AGREEMENT" VARCHAR2(1000 BYTE) NULL ,
"ENTRUST_PERSONNEL_LIST" VARCHAR2(1000 BYTE) NULL ,
"SHAREHOLDER_FUNDING" VARCHAR2(1000 BYTE) NULL ,
"BUSINESS_MODEL" VARCHAR2(1000 BYTE) NULL ,
"SPECIAL_BUSINESS_CERTIFICATE" VARCHAR2(1000 BYTE) NULL ,
"BUSINESS_INFO" VARCHAR2(1000 BYTE) NULL ,
"OFFICE_SCENE_PHOTO" VARCHAR2(1000 BYTE) NULL ,
"DOORPLATE_PHOTO" VARCHAR2(1000 BYTE) NULL ,
"WEBSITE_HOMEPAGE" VARCHAR2(1000 BYTE) NULL ,
"WEBSITE_ORDER_PAGE" VARCHAR2(1000 BYTE) NULL ,
"CUSTOMS_REGISTRATION" VARCHAR2(1000 BYTE) NULL ,
"FOREIGN_TRADE_REGISTRATION" VARCHAR2(1000 BYTE) NULL ,
"LOGISTICS_COMPACT" VARCHAR2(1000 BYTE) NULL ,
"MOBAO_OUT_CROSS_BORDER_PAYMENT" VARCHAR2(1000 BYTE) NULL ,
"MOBAO_CROSS_BORDER_PAYMENT" VARCHAR2(1000 BYTE) NULL ,
"INDIVIDUAL_IDENTITY_CHECK" VARCHAR2(1000 BYTE) NULL ,
"OVERSEAS_WEBSITE_ARCHIVAL" VARCHAR2(1000 BYTE) NULL ,
"DEPEND_PLATFORM_COMPACT" VARCHAR2(1000 BYTE) NULL ,
"CROSS_BORDER_MERCHANT_COMPACT" VARCHAR2(1000 BYTE) NULL ,
"MERCHANT_COMPACT" VARCHAR2(1000 BYTE) NULL ,
"GOVERNMENT_BUSINESS_CERTIFY" VARCHAR2(1000 BYTE) NULL ,
"CORP_IDENTITY" VARCHAR2(1000 BYTE) NULL ,
"WAREHOUSE_PHOTO" VARCHAR2(1000 BYTE) NULL ,
"STOCK_CHANNEL_CERTIFY" VARCHAR2(1000 BYTE) NULL ,
"DUE_BANK_ACCOUNT_CERTIFY" VARCHAR2(1000 BYTE) NULL ,
"OTHERS" VARCHAR2(1000 BYTE) NULL ,
"SUPPLEMENT" CLOB NULL ,
"CUSTOMER_NO" VARCHAR2(20 BYTE) NULL ,
"CREATE_TIME" CHAR(19 BYTE) NULL ,
"UPDATE_TIME" CHAR(19 BYTE) NULL ,
"AUDIT_EVENT_ID" NUMBER(16) NULL ,
"UPDATE_RECORD" VARCHAR2(4000 BYTE) NULL 
);
COMMENT ON COLUMN "AUDIT_MERCHANT_ELECTRONIC_DATA"."UPDATE_RECORD" IS '修改记录';
ALTER TABLE "AUDIT_MERCHANT_ELECTRONIC_DATA" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "AUDIT_MERCHANT_ELECTRONIC_DATA" ADD PRIMARY KEY ("ID");


--商户费率（审核）
CREATE SEQUENCE  "SEQ_AUDIT_MERCHANT_FEE_RATE"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE TABLE "AUDIT_MERCHANT_FEE_RATE" (
"ID" NUMBER(16) NOT NULL ,
"AUDIT_EVENT_ID" NUMBER(16) NULL ,
"CUSTOMER_NO" VARCHAR2(20 BYTE) NULL ,
"PRODUCT_KIND" VARCHAR2(30 BYTE) NULL ,
"PAY_TYPE" VARCHAR2(5 BYTE) NULL ,
"BANK_CODE" VARCHAR2(20 BYTE) NULL ,
"FEE_TYPE" CHAR(1 BYTE) NULL ,
"FEE_RATE" VARCHAR2(20 BYTE) NULL ,
"MIN_FEE" VARCHAR2(20 BYTE) NULL ,
"MAX_FEE" VARCHAR2(20 BYTE) NULL ,
"START_DATE" CHAR(10 BYTE) NULL ,
"END_DATE" CHAR(10 BYTE) NULL ,
"IF_EFFECTIVE" CHAR(1 BYTE) NULL ,
"CREATE_TIME" CHAR(19 BYTE) NULL ,
"UPDATE_TIME" CHAR(19 BYTE) NULL ,
"FORMAL_ID" NUMBER(16) NULL ,
"FIXED_AMOUNT" VARCHAR2(20 BYTE) NULL 
);
COMMENT ON COLUMN "AUDIT_MERCHANT_FEE_RATE"."FORMAL_ID" IS '对应已审核通过正式数据的ID';
ALTER TABLE "AUDIT_MERCHANT_FEE_RATE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "AUDIT_MERCHANT_FEE_RATE" ADD PRIMARY KEY ("ID");


--商户即时结算（审核）
CREATE SEQUENCE  "SEQ_A_MERCHANT_FUND_SETTLEMENT"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE TABLE "AUDIT_MERCHANT_FUND_SETTLEMENT" (
"ID" NUMBER(16) NOT NULL ,
"CUSTOMER_NO" VARCHAR2(20 BYTE) NULL ,
"OPEN_FUND_SETTLEMENT" VARCHAR2(30 BYTE) NULL ,
"FEE_TYPE" CHAR(1 BYTE) NULL ,
"FEE_RATE" VARCHAR2(20 BYTE) NULL ,
"FIXED_AMOUNT" VARCHAR2(20 BYTE) NULL ,
"SINGLE_DAY_MAX_FUND" VARCHAR2(20 BYTE) NULL ,
"FUND_SETTLEMENT_SCALE" VARCHAR2(20 BYTE) NULL ,
"CREATE_TIME" VARCHAR2(19 BYTE) NULL ,
"UPDATE_TIME" VARCHAR2(19 BYTE) NULL ,
"UPDATE_RECORD" VARCHAR2(4000 BYTE) NULL ,
"AUDIT_EVENT_ID" NUMBER(16) NULL ,
"FORMAL_ID" NUMBER(16) NULL ,
"CUSTOMER_NAME" VARCHAR2(100 BYTE) NULL 
);
COMMENT ON COLUMN "AUDIT_MERCHANT_FUND_SETTLEMENT"."CUSTOMER_NO" IS '客户号';
COMMENT ON COLUMN "AUDIT_MERCHANT_FUND_SETTLEMENT"."OPEN_FUND_SETTLEMENT" IS '开通垫资结算 (1-T0  2-D0   0-关闭)';
COMMENT ON COLUMN "AUDIT_MERCHANT_FUND_SETTLEMENT"."FEE_TYPE" IS '计费方式 （数据字典：fee_type 1-固定值 2-按比例';
COMMENT ON COLUMN "AUDIT_MERCHANT_FUND_SETTLEMENT"."FEE_RATE" IS '费率 （计费方式为“按比例”时赋值）';
COMMENT ON COLUMN "AUDIT_MERCHANT_FUND_SETTLEMENT"."FIXED_AMOUNT" IS '固定金额 （计费方式为“固定值”时赋值）';
COMMENT ON COLUMN "AUDIT_MERCHANT_FUND_SETTLEMENT"."SINGLE_DAY_MAX_FUND" IS '单日最高垫资金额';
COMMENT ON COLUMN "AUDIT_MERCHANT_FUND_SETTLEMENT"."FUND_SETTLEMENT_SCALE" IS '垫资结算比例';
COMMENT ON COLUMN "AUDIT_MERCHANT_FUND_SETTLEMENT"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "AUDIT_MERCHANT_FUND_SETTLEMENT"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "AUDIT_MERCHANT_FUND_SETTLEMENT"."UPDATE_RECORD" IS '更新记录';
COMMENT ON COLUMN "AUDIT_MERCHANT_FUND_SETTLEMENT"."AUDIT_EVENT_ID" IS '审核事件id';
COMMENT ON COLUMN "AUDIT_MERCHANT_FUND_SETTLEMENT"."FORMAL_ID" IS '对应已审核通过正式数据的ID';
COMMENT ON COLUMN "AUDIT_MERCHANT_FUND_SETTLEMENT"."CUSTOMER_NAME" IS '商户全称';
ALTER TABLE "AUDIT_MERCHANT_FUND_SETTLEMENT" ADD PRIMARY KEY ("ID");


--商户基本信息
CREATE SEQUENCE  "SEQ_AUDIT_MERCHANT_INFO"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE TABLE "AUDIT_MERCHANT_INFO" (
"ID" NUMBER(16) NOT NULL ,
"CUSTOMER_NO" VARCHAR2(20 BYTE) NULL ,
"PLATFORM_CUSTOMER_NO" VARCHAR2(20 BYTE) NULL ,
"SHORT_NAME" VARCHAR2(70 BYTE) NULL ,
"NAME" VARCHAR2(70 BYTE) NULL ,
"STATUS" VARCHAR2(2 BYTE) NULL ,
"SHAREHOLDER" VARCHAR2(100 BYTE) NULL ,
"SHAREHOLDER_ID_NUM" VARCHAR2(50 BYTE) NULL ,
"LEGAL_PERSON" VARCHAR2(40 BYTE) NULL ,
"LEGAL_PERSON_CERT_TYPE" CHAR(1 BYTE) NULL ,
"LEGAL_PERSON_CERT_NUM" VARCHAR2(50 BYTE) NULL ,
"LEGAL_PERSON_CERT_PERIOD_START" CHAR(10 BYTE) NULL ,
"LEGAL_PERSON_SEX" CHAR(1 BYTE) NULL ,
"LEGAL_PERSON_CAREER" VARCHAR2(20 BYTE) NULL ,
"LEGAL_PERSON_NATIONALITY" VARCHAR2(10 BYTE) NULL ,
"BUSINESS_LICENCE_NO" VARCHAR2(100 BYTE) NULL ,
"BUSINESS_LICENCE_PERIOD_START" CHAR(10 BYTE) NULL ,
"REGISTERED_FUND" VARCHAR2(20 BYTE) NULL ,
"BUSINESS_SCOPE" VARCHAR2(3000 BYTE) NULL ,
"CONTACT_PERSON" VARCHAR2(30 BYTE) NULL ,
"CONTACT_PHONE" VARCHAR2(20 BYTE) NULL ,
"ADDRESS" VARCHAR2(400 BYTE) NULL ,
"ECOMMERCE_DOMAIN" VARCHAR2(30 BYTE) NULL ,
"ICP" VARCHAR2(100 BYTE) NULL ,
"ICP_PERIOD_START" CHAR(10 BYTE) NULL ,
"INDUSTRY_CODE" VARCHAR2(5 BYTE) NULL ,
"AREA_CODE" VARCHAR2(5 BYTE) NULL ,
"SALESMAN_NO" CHAR(4 BYTE) NULL ,
"SALESMAN_NAME" VARCHAR2(10 BYTE) NULL ,
"AGENT_NO" VARCHAR2(20 BYTE) NULL ,
"AGENT_NAME" VARCHAR2(30 BYTE) NULL ,
"MERCHANT_TYPE" CHAR(1 BYTE) NULL ,
"STAFF" VARCHAR2(30 BYTE) NULL ,
"STAFF_CERT_TYPE" CHAR(1 BYTE) NULL ,
"STAFF_CERT_NUM" VARCHAR2(100 BYTE) NULL ,
"STAFF_CERT_PERIOD_START" CHAR(10 BYTE) NULL ,
"IF_SUBMIT_CUSTOMS" CHAR(1 BYTE) NULL ,
"CUSTOMS" CHAR(1 BYTE) NULL ,
"CUSTOMS_REGISTER_NO" VARCHAR2(30 BYTE) NULL ,
"EXIT_BUSINESS_MODEL" CHAR(1 BYTE) NULL ,
"ECOMMERCE_WEBSITE_NAME" VARCHAR2(50 BYTE) NULL ,
"CREATE_TIME" CHAR(19 BYTE) NULL ,
"UPDATE_TIME" CHAR(19 BYTE) NULL ,
"LOCK_TIME" CHAR(19 BYTE) NULL ,
"CANCEL_TIME" CHAR(19 BYTE) NULL ,
"AUDIT_EVENT_ID" NUMBER(16) NULL ,
"BRANCH_NO" CHAR(3 BYTE) NULL ,
"MERCHANT_ATTRIBUTE" VARCHAR2(20 BYTE) NULL ,
"MERCHANT_PROPERTY" CHAR(1 BYTE) NULL ,
"LEGAL_PERSON_CERT_PERIOD_END" CHAR(10 BYTE) NULL ,
"BUSINESS_LICENCE_PERIOD_END" CHAR(10 BYTE) NULL ,
"MERCHANT_DOMAIN" VARCHAR2(200 BYTE) NULL ,
"ICP_PERIOD_END" CHAR(10 BYTE) NULL ,
"STAFF_CERT_PERIOD_END" CHAR(10 BYTE) NULL ,
"CROSS_BORDER_ENTRANCE" VARCHAR2(20 BYTE) NULL ,
"INDUSTRY_NAME" VARCHAR2(100 BYTE) NULL ,
"BUSINESS_KIND" CHAR(1 BYTE) NULL ,
"BUSINESS_TYPE" VARCHAR2(20 BYTE) NULL ,
"MCC_CODE" VARCHAR2(10 BYTE) NULL ,
"MCC_KIND_NAME" VARCHAR2(100 BYTE) NULL ,
"WECHAT_BUSINESS_KIND_CODE" VARCHAR2(10 BYTE) NULL ,
"WECHAT_BUSINESS_KIND_NAME" VARCHAR2(100 BYTE) NULL ,
"NUCC_BUSINESS_KIND_CODE" VARCHAR2(10 BYTE) NULL ,
"NUCC_BUSINESS_KIND_NAME" VARCHAR2(100 BYTE) NULL ,
"ALIPAY_BUSINESS_KIND" VARCHAR2(20 BYTE) NULL ,
"CONTACT_CERT_NUM" VARCHAR2(50 BYTE) NULL ,
"CONTACT_ID_PERIOD_START" CHAR(10 BYTE) NULL ,
"CONTACT_ID_PERIOD_END" CHAR(10 BYTE) NULL ,
"CUSTOMER_TEL" VARCHAR2(30 BYTE) NULL ,
"UPDATE_RECORD" CLOB NULL ,
"CONTACT_EMAIL" VARCHAR2(30 BYTE) NULL ,
"BUSINESS_TYPE_DIC" VARCHAR2(255 BYTE) NULL ,
"CUP_BUSINESS_KIND" VARCHAR2(10 BYTE) NULL ,
"AUDIT_ADVICE" VARCHAR2(4000 BYTE) NULL
);
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."CUSTOMER_NO" IS '客户号';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."SHORT_NAME" IS '商户简称';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."NAME" IS '商户全称';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."STATUS" IS '商户状态（数据字典 merchant_status：0-初始 1-活动 2-账号激活 3-注销）';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."SHAREHOLDER" IS '控股股东或实际控制人';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."SHAREHOLDER_ID_NUM" IS '股东身份证号';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."LEGAL_PERSON" IS '法人代表';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."LEGAL_PERSON_CERT_TYPE" IS '法人证件类型（数据字典 certificate_type：0-身份证 1-护照）';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."LEGAL_PERSON_CERT_NUM" IS '法人证件编号';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."LEGAL_PERSON_CERT_PERIOD_START" IS '法人证件有效期';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."LEGAL_PERSON_SEX" IS '法人性别（数据字典 sex：0-男 1-女）';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."LEGAL_PERSON_CAREER" IS '法人职业（数据字典 occupation）';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."LEGAL_PERSON_NATIONALITY" IS '法人国籍（数据字典 nationality）';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."BUSINESS_LICENCE_NO" IS '营业执照号';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."BUSINESS_LICENCE_PERIOD_START" IS '营业执照有效期';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."REGISTERED_FUND" IS '注册资金';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."BUSINESS_SCOPE" IS '经营范围';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."CONTACT_PERSON" IS '联系人';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."CONTACT_PHONE" IS '联系电话';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."ADDRESS" IS '商户地址';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."ECOMMERCE_DOMAIN" IS '备案域名/电商网站域名';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."ICP" IS 'ICP备案号';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."ICP_PERIOD_START" IS 'ICP备案到期日';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."INDUSTRY_CODE" IS '所属行业（关联"行业信息"模块IndustryInfo）';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."AREA_CODE" IS '所属地区(数据字典 area_code)';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."SALESMAN_NO" IS '所属销售（关联销售信息）';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."SALESMAN_NAME" IS '所属销售姓名（冗余设计）';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."AGENT_NO" IS '所属代理 （关联代理信息）';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."AGENT_NAME" IS '所属代理名称 （冗余设计）';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."MERCHANT_TYPE" IS '商户类型(数据字典 merchant_type：1-个人，2-企业)';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."STAFF" IS '授权办理业务人员的姓名';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."STAFF_CERT_TYPE" IS '授权办理业务人员证件类型（数据字典 certificate_type：0-身份证 1-护照）';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."STAFF_CERT_NUM" IS '授权办理业务人员证件号';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."STAFF_CERT_PERIOD_START" IS '授权办理业务人员证件有效期';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."IF_SUBMIT_CUSTOMS" IS '是否报送海关：0-报送，1-不报送';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."CUSTOMS" IS '报送海关（数据字典 default_customs：0-四川 1-成都）';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."CUSTOMS_REGISTER_NO" IS '海关登记编号';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."EXIT_BUSINESS_MODEL" IS '出口业务模式（数据字典 exit_business_model：1-企业自建站，2-挂靠电商平台';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."ECOMMERCE_WEBSITE_NAME" IS '电商网站名称';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."LOCK_TIME" IS '锁定时间';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."CANCEL_TIME" IS '注销时间';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."AUDIT_EVENT_ID" IS '审核事件ID，关联审核事件表';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."BRANCH_NO" IS '分支机构号';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."MERCHANT_ATTRIBUTE" IS '商户属性';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."LEGAL_PERSON_CERT_PERIOD_END" IS '法人证件有效期结束时间';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."MERCHANT_DOMAIN" IS '商户域名';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."ICP_PERIOD_END" IS 'ICP备案有效日期结束时间';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."CROSS_BORDER_ENTRANCE" IS '跨境进口商户属性';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."INDUSTRY_NAME" IS '所属行业名称';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."BUSINESS_KIND" IS '业务种类（数据字典 business_kind：1-互联网，2-移动支付）';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."BUSINESS_TYPE" IS '业务类型(数据字典 merchant_business_type：1-普通业务，2-跨境进口，3-跨境出口，4-跨境通关)';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."MCC_CODE" IS 'MCC代码（关联MCC表）';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."MCC_KIND_NAME" IS 'MCC类目名称（冗余设计）';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."WECHAT_BUSINESS_KIND_CODE" IS '微信经营类目代码（关联微信经营类目表）';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."WECHAT_BUSINESS_KIND_NAME" IS '微信经营类目名称（冗余设计）';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."NUCC_BUSINESS_KIND_CODE" IS '网联业务种类代码（关联网联业务种类表）';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."NUCC_BUSINESS_KIND_NAME" IS '网联业务种类名称';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."ALIPAY_BUSINESS_KIND" IS '支付宝经营类目（数据字典 alipay_business_kind）';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."CONTACT_CERT_NUM" IS '联系人身份证号码';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."CONTACT_ID_PERIOD_START" IS '联系人身份证有效期开始时间';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."CONTACT_ID_PERIOD_END" IS '联系人身份证有效期结束时间';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."CUSTOMER_TEL" IS '客服电话';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."UPDATE_RECORD" IS '更新记录';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."BUSINESS_TYPE_DIC" IS '业务类型(中文名称)';
COMMENT ON COLUMN "AUDIT_MERCHANT_INFO"."CUP_BUSINESS_KIND" IS '银联业务种类';
ALTER TABLE "AUDIT_MERCHANT_INFO" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "AUDIT_MERCHANT_INFO" ADD PRIMARY KEY ("ID");



--商户路由
CREATE SEQUENCE  "SEQ_AUDIT_MERCHANT_ROUTE"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE TABLE "AUDIT_MERCHANT_ROUTE" (
"ID" NUMBER(16) NOT NULL ,
"AUDIT_EVENT_ID" NUMBER(16) NULL ,
"FORMAL_ID" NUMBER(16) NULL ,
"CUSTOMER_NO" VARCHAR2(20 BYTE) NULL ,
"CUSTOMER_NAME" VARCHAR2(100 BYTE) NULL ,
"TRADE_TYPE" CHAR(1 BYTE) NULL ,
"PAY_TYPES" VARCHAR2(255 BYTE) NULL ,
"BANK_CODES" VARCHAR2(255 BYTE) NULL ,
"MIN_AMOUNT" VARCHAR2(20 BYTE) NULL ,
"MAX_AMOUNT" VARCHAR2(20 BYTE) NULL ,
"CHANNEL_CODE" VARCHAR2(30 BYTE) NULL ,
"CHANNEL_MERCHANT_NO" VARCHAR2(30 BYTE) NULL ,
"CHANNEL_MERCHANT_NAME" VARCHAR2(100 BYTE) NULL ,
"RULE" VARCHAR2(300 BYTE) NULL ,
"IF_EFFCTIVE" CHAR(1 BYTE) NULL ,
"CREATE_TIME" CHAR(19 BYTE) NULL ,
"UPDATE_TIME" CHAR(19 BYTE) NULL ,
"PAY_TYPES_DIC" VARCHAR2(255 BYTE) NULL ,
"BANK_CODES_DIC" VARCHAR2(255 BYTE) NULL ,
"UPDATE_RECORD" VARCHAR2(255 BYTE) NULL ,
"PRIORITY" CHAR(1 BYTE) NULL 
);
COMMENT ON TABLE "AUDIT_MERCHANT_ROUTE" IS '商户消费路由';
COMMENT ON COLUMN "AUDIT_MERCHANT_ROUTE"."AUDIT_EVENT_ID" IS '审核事件ID';
COMMENT ON COLUMN "AUDIT_MERCHANT_ROUTE"."FORMAL_ID" IS '对应已审核通过正式数据的ID';
COMMENT ON COLUMN "AUDIT_MERCHANT_ROUTE"."CUSTOMER_NO" IS '客户号';
COMMENT ON COLUMN "AUDIT_MERCHANT_ROUTE"."CUSTOMER_NAME" IS '客户全称（冗余设计）';
COMMENT ON COLUMN "AUDIT_MERCHANT_ROUTE"."TRADE_TYPE" IS '交易类型（1：消费 2：出款 ）';
COMMENT ON COLUMN "AUDIT_MERCHANT_ROUTE"."PAY_TYPES" IS '支付方式（多选，逗号分开）';
COMMENT ON COLUMN "AUDIT_MERCHANT_ROUTE"."BANK_CODES" IS '支持银行（多选，以逗号分隔银行编码存储）';
COMMENT ON COLUMN "AUDIT_MERCHANT_ROUTE"."MIN_AMOUNT" IS '金额区间（最小金额）';
COMMENT ON COLUMN "AUDIT_MERCHANT_ROUTE"."MAX_AMOUNT" IS '金额区间（最大金额）';
COMMENT ON COLUMN "AUDIT_MERCHANT_ROUTE"."CHANNEL_CODE" IS '通道编码';
COMMENT ON COLUMN "AUDIT_MERCHANT_ROUTE"."CHANNEL_MERCHANT_NO" IS '通道商户号';
COMMENT ON COLUMN "AUDIT_MERCHANT_ROUTE"."CHANNEL_MERCHANT_NAME" IS '通道商户名称（冗余设计）';
COMMENT ON COLUMN "AUDIT_MERCHANT_ROUTE"."RULE" IS '规则描述';
COMMENT ON COLUMN "AUDIT_MERCHANT_ROUTE"."IF_EFFCTIVE" IS '是否有效（0：无效 1：有效）';
COMMENT ON COLUMN "AUDIT_MERCHANT_ROUTE"."PAY_TYPES_DIC" IS '支付方式(中文名称)';
COMMENT ON COLUMN "AUDIT_MERCHANT_ROUTE"."BANK_CODES_DIC" IS '支持银行编码(中文名称)';
COMMENT ON COLUMN "AUDIT_MERCHANT_ROUTE"."UPDATE_RECORD" IS '修改记录';
COMMENT ON COLUMN "AUDIT_MERCHANT_ROUTE"."PRIORITY" IS '优先级';
ALTER TABLE "AUDIT_MERCHANT_ROUTE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "AUDIT_MERCHANT_ROUTE" ADD PRIMARY KEY ("ID");


--商户结算信息
CREATE SEQUENCE  "SEQ_AUDIT_SETTLEMENT_INFO"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE TABLE "AUDIT_MERCHANT_SETTLEMENT_INFO" (
"ID" NUMBER(16) NOT NULL ,
"AUDIT_EVENT_ID" NUMBER(16) NULL ,
"CUSTOMER_NO" VARCHAR2(20 BYTE) NULL ,
"BANK_ACCOUNT_NAME" VARCHAR2(100 BYTE) NULL ,
"PAYEE_ID_NUM" VARCHAR2(50 BYTE) NULL ,
"ACCOUNT_NO" VARCHAR2(50 BYTE) NULL ,
"RESERVE_MOBILE_NO" VARCHAR2(50 BYTE) NULL ,
"BANK_NO" VARCHAR2(10 BYTE) NULL ,
"BANK_NAME" VARCHAR2(90 BYTE) NULL ,
"ACCOUNT_TYPE" CHAR(1 BYTE) NULL ,
"BRANCH_BANK_NO" VARCHAR2(15 BYTE) NULL ,
"BRANCH_BANK_NAME" VARCHAR2(90 BYTE) NULL ,
"CREATE_TIME" CHAR(19 BYTE) NULL ,
"UPDATE_TIME" CHAR(19 BYTE) NULL ,
"UPDATE_RECORD" VARCHAR2(4000 BYTE) NULL ,
"PROVINCE" VARCHAR2(100 BYTE) NULL ,
"PROVINCE_CODE" VARCHAR2(5 BYTE) NULL ,
"CITY" VARCHAR2(100 BYTE) NULL ,
"CITY_CODE" VARCHAR2(5 BYTE) NULL 
);
COMMENT ON TABLE "AUDIT_MERCHANT_SETTLEMENT_INFO" IS '商户结算信息';
COMMENT ON COLUMN "AUDIT_MERCHANT_SETTLEMENT_INFO"."CUSTOMER_NO" IS '客户号（商户1开头，个人5开头）';
COMMENT ON COLUMN "AUDIT_MERCHANT_SETTLEMENT_INFO"."BANK_ACCOUNT_NAME" IS '开户户名';
COMMENT ON COLUMN "AUDIT_MERCHANT_SETTLEMENT_INFO"."PAYEE_ID_NUM" IS '收款人身份证号';
COMMENT ON COLUMN "AUDIT_MERCHANT_SETTLEMENT_INFO"."ACCOUNT_NO" IS '开户账号';
COMMENT ON COLUMN "AUDIT_MERCHANT_SETTLEMENT_INFO"."RESERVE_MOBILE_NO" IS '银行预留手机号';
COMMENT ON COLUMN "AUDIT_MERCHANT_SETTLEMENT_INFO"."BANK_NO" IS '开户行行号';
COMMENT ON COLUMN "AUDIT_MERCHANT_SETTLEMENT_INFO"."BANK_NAME" IS '开户行名称';
COMMENT ON COLUMN "AUDIT_MERCHANT_SETTLEMENT_INFO"."ACCOUNT_TYPE" IS '账户类型（1：对私 2：对公）';
COMMENT ON COLUMN "AUDIT_MERCHANT_SETTLEMENT_INFO"."BRANCH_BANK_NO" IS '分支行行号';
COMMENT ON COLUMN "AUDIT_MERCHANT_SETTLEMENT_INFO"."BRANCH_BANK_NAME" IS '分支行名称';
COMMENT ON COLUMN "AUDIT_MERCHANT_SETTLEMENT_INFO"."PROVINCE" IS '省名称';
COMMENT ON COLUMN "AUDIT_MERCHANT_SETTLEMENT_INFO"."PROVINCE_CODE" IS '省代码';
COMMENT ON COLUMN "AUDIT_MERCHANT_SETTLEMENT_INFO"."CITY" IS '市名称';
COMMENT ON COLUMN "AUDIT_MERCHANT_SETTLEMENT_INFO"."CITY_CODE" IS '市代码';
ALTER TABLE "AUDIT_MERCHANT_SETTLEMENT_INFO" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "AUDIT_MERCHANT_SETTLEMENT_INFO" ADD PRIMARY KEY ("ID");


--代理基本信息
CREATE SEQUENCE  "SEQ_BAS_AGENT_BASIC_INFO"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE TABLE "BAS_AGENT_BASIC_INFO" (
"ID" NUMBER(16) NOT NULL ,
"NAME" VARCHAR2(50 BYTE) NULL ,
"SHORT_NAME" VARCHAR2(15 BYTE) NULL ,
"LEGAL_PERSON" VARCHAR2(40 BYTE) NULL ,
"LEGAL_PERSON_NATIONALITY" VARCHAR2(20 BYTE) NULL ,
"LEGAL_PERSON_CERT_TYPE" CHAR(1 BYTE) NULL ,
"LEGAL_PERSON_CERT_NUM" VARCHAR2(50 BYTE) NULL ,
"LEGAL_PERSON_CERT_PERIOD_START" CHAR(10 BYTE) NULL ,
"LEGAL_PERSON_CERT_PERIOD_END" CHAR(10 BYTE) NULL ,
"BUSINESS_LICENCE_NO" VARCHAR2(30 BYTE) NULL ,
"BUSINESS_LICENCE_PERIOD_START" CHAR(10 BYTE) NULL ,
"BUSINESS_LICENCE_PERIOD_END" CHAR(10 BYTE) NULL ,
"REGISTERED_FUND" VARCHAR2(20 BYTE) NULL ,
"BUSINESS_SCOPE" VARCHAR2(3000 BYTE) NULL ,
"AGENT_ADDRESS" VARCHAR2(400 BYTE) NULL ,
"AGENT_PLATFORM_URL" VARCHAR2(150 BYTE) NULL ,
"CONTACT_PERSON" VARCHAR2(30 BYTE) NULL ,
"CONTACT_PHONE" VARCHAR2(20 BYTE) NULL ,
"AGENT_NO" VARCHAR2(20 BYTE) NULL ,
"CREATE_TIME" CHAR(19 BYTE) NULL ,
"UPDATE_TIME" CHAR(19 BYTE) NULL ,
"CONTACT_CERT_NUM" VARCHAR2(50 BYTE) NULL ,
"CONTACT_ID_PERIOD_START" CHAR(10 BYTE) NULL ,
"CONTACT_ID_PERIOD_END" CHAR(10 BYTE) NULL ,
"AGENT_STATUS" CHAR(1 BYTE) NULL ,
"BRANCH_NO" CHAR(3 BYTE) NULL 
);
COMMENT ON COLUMN "BAS_AGENT_BASIC_INFO"."NAME" IS '代理商全称';
COMMENT ON COLUMN "BAS_AGENT_BASIC_INFO"."SHORT_NAME" IS '代理商简称';
COMMENT ON COLUMN "BAS_AGENT_BASIC_INFO"."LEGAL_PERSON" IS '法人代表';
COMMENT ON COLUMN "BAS_AGENT_BASIC_INFO"."LEGAL_PERSON_NATIONALITY" IS '法人国籍（数据字典 nationality）';
COMMENT ON COLUMN "BAS_AGENT_BASIC_INFO"."LEGAL_PERSON_CERT_TYPE" IS '法人证件类型（数据字典 certificate_type：0-身份证 1-护照）';
COMMENT ON COLUMN "BAS_AGENT_BASIC_INFO"."LEGAL_PERSON_CERT_NUM" IS '法人证件号';
COMMENT ON COLUMN "BAS_AGENT_BASIC_INFO"."LEGAL_PERSON_CERT_PERIOD_START" IS '法人证件有效期开始时间';
COMMENT ON COLUMN "BAS_AGENT_BASIC_INFO"."LEGAL_PERSON_CERT_PERIOD_END" IS '法人证件有效期结束时间';
COMMENT ON COLUMN "BAS_AGENT_BASIC_INFO"."BUSINESS_LICENCE_NO" IS '营业执照号';
COMMENT ON COLUMN "BAS_AGENT_BASIC_INFO"."BUSINESS_LICENCE_PERIOD_START" IS '营业执照有效期开始时间';
COMMENT ON COLUMN "BAS_AGENT_BASIC_INFO"."BUSINESS_LICENCE_PERIOD_END" IS '营业执照有效期结束时间';
COMMENT ON COLUMN "BAS_AGENT_BASIC_INFO"."REGISTERED_FUND" IS '注册资金';
COMMENT ON COLUMN "BAS_AGENT_BASIC_INFO"."BUSINESS_SCOPE" IS '企业经营范围';
COMMENT ON COLUMN "BAS_AGENT_BASIC_INFO"."AGENT_ADDRESS" IS '代理商地址';
COMMENT ON COLUMN "BAS_AGENT_BASIC_INFO"."AGENT_PLATFORM_URL" IS '代理平台网址';
COMMENT ON COLUMN "BAS_AGENT_BASIC_INFO"."CONTACT_PERSON" IS '联系人';
COMMENT ON COLUMN "BAS_AGENT_BASIC_INFO"."CONTACT_PHONE" IS '联系电话';
COMMENT ON COLUMN "BAS_AGENT_BASIC_INFO"."AGENT_NO" IS '代理商号';
COMMENT ON COLUMN "BAS_AGENT_BASIC_INFO"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "BAS_AGENT_BASIC_INFO"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "BAS_AGENT_BASIC_INFO"."CONTACT_CERT_NUM" IS '联系人身份证号码';
COMMENT ON COLUMN "BAS_AGENT_BASIC_INFO"."CONTACT_ID_PERIOD_START" IS '联系人身份证有效期开始时间';
COMMENT ON COLUMN "BAS_AGENT_BASIC_INFO"."CONTACT_ID_PERIOD_END" IS '联系人身份证有效期结束时间';
COMMENT ON COLUMN "BAS_AGENT_BASIC_INFO"."AGENT_STATUS" IS '代理状态';
COMMENT ON COLUMN "BAS_AGENT_BASIC_INFO"."BRANCH_NO" IS '分支机构号';
ALTER TABLE "BAS_AGENT_BASIC_INFO" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "BAS_AGENT_BASIC_INFO" ADD PRIMARY KEY ("ID");


--通道费率
CREATE SEQUENCE  "SEQ_BAS_CHANNEL_FEE_RATE"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE TABLE "BAS_CHANNEL_FEE_RATE" (
"ID" NUMBER(16) NOT NULL ,
"CHANNEL_CODE" VARCHAR2(20 BYTE) NULL ,
"CHANNEL_MERCHANT_NO" VARCHAR2(20 BYTE) NULL ,
"PRODUCT_KIND" VARCHAR2(5 BYTE) NULL ,
"PAY_TYPE" VARCHAR2(5 BYTE) NULL ,
"BANK_CODE" VARCHAR2(20 BYTE) NULL ,
"FEE_TYPE" CHAR(1 BYTE) NULL ,
"FEE_RATE" VARCHAR2(20 BYTE) NULL ,
"MIN_FEE" VARCHAR2(20 BYTE) NULL ,
"MAX_FEE" VARCHAR2(20 BYTE) NULL ,
"START_DATE" CHAR(10 BYTE) NULL ,
"END_DATE" CHAR(10 BYTE) NULL ,
"CREATE_TIME" CHAR(19 BYTE) NULL ,
"UPDATE_TIME" CHAR(19 BYTE) NULL ,
"FIXED_AMOUNT" VARCHAR2(20 BYTE) NULL ,
"STATUS" CHAR(1 BYTE) NULL ,
"CHANNEL_MERCHANT_NAME" VARCHAR2(50 BYTE) NULL ,
"FORMAL_ID" NUMBER(16) NULL 
);
COMMENT ON COLUMN "BAS_CHANNEL_FEE_RATE"."CHANNEL_CODE" IS '通道号';
COMMENT ON COLUMN "BAS_CHANNEL_FEE_RATE"."CHANNEL_MERCHANT_NO" IS '通道商户号';
COMMENT ON COLUMN "BAS_CHANNEL_FEE_RATE"."PRODUCT_KIND" IS '产品类型';
COMMENT ON COLUMN "BAS_CHANNEL_FEE_RATE"."PAY_TYPE" IS '支付方式';
COMMENT ON COLUMN "BAS_CHANNEL_FEE_RATE"."BANK_CODE" IS '配置银行';
COMMENT ON COLUMN "BAS_CHANNEL_FEE_RATE"."FEE_TYPE" IS '计费方式';
COMMENT ON COLUMN "BAS_CHANNEL_FEE_RATE"."FEE_RATE" IS '比例（计费方式为“按比例”时赋值）';
COMMENT ON COLUMN "BAS_CHANNEL_FEE_RATE"."MIN_FEE" IS '保底';
COMMENT ON COLUMN "BAS_CHANNEL_FEE_RATE"."MAX_FEE" IS '封顶';
COMMENT ON COLUMN "BAS_CHANNEL_FEE_RATE"."START_DATE" IS '生效日期';
COMMENT ON COLUMN "BAS_CHANNEL_FEE_RATE"."END_DATE" IS '失效事件';
COMMENT ON COLUMN "BAS_CHANNEL_FEE_RATE"."FIXED_AMOUNT" IS '固定金额 （计费方式为“固定值”时赋值）';
COMMENT ON COLUMN "BAS_CHANNEL_FEE_RATE"."STATUS" IS '状态（0-初始；1-激活；2-停用）';
COMMENT ON COLUMN "BAS_CHANNEL_FEE_RATE"."CHANNEL_MERCHANT_NAME" IS '通道商户名称';
COMMENT ON COLUMN "BAS_CHANNEL_FEE_RATE"."FORMAL_ID" IS '正式费率id标识';
ALTER TABLE "BAS_CHANNEL_FEE_RATE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "BAS_CHANNEL_FEE_RATE" ADD PRIMARY KEY ("ID");


--商户中心公告
CREATE SEQUENCE  "SEQ_MERCHANT_CENTER_NOTICE"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE TABLE "BAS_MERCHANT_CENTER_NOTICE" (
"ID" NUMBER(16) NOT NULL ,
"TITLE" VARCHAR2(150 BYTE) NULL ,
"CONTENT" CLOB NULL ,
"CREATE_TIME" CHAR(19 BYTE) NULL ,
"UPDATE_TIME" CHAR(19 BYTE) NULL 
);
COMMENT ON TABLE "BAS_MERCHANT_CENTER_NOTICE" IS '商户中心公告';
COMMENT ON COLUMN "BAS_MERCHANT_CENTER_NOTICE"."TITLE" IS '公告标题';
COMMENT ON COLUMN "BAS_MERCHANT_CENTER_NOTICE"."CONTENT" IS '公告内容';
ALTER TABLE "BAS_MERCHANT_CENTER_NOTICE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "BAS_MERCHANT_CENTER_NOTICE" ADD PRIMARY KEY ("ID");


--商户中心账号
CREATE SEQUENCE  "SEQ_M_C_A"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE TABLE "BAS_MERCHANT_CENTRE_ACCOUNT" (
"ID" NUMBER(16) NOT NULL ,
"CUSTOMER_NO" VARCHAR2(20 BYTE) NULL ,
"MANAGER_EMAIL" VARCHAR2(50 BYTE) NULL ,
"MANAGER_TEL" VARCHAR2(20 BYTE) NULL ,
"CREATE_TIME" CHAR(19 BYTE) NULL ,
"UPDATE_TIME" CHAR(19 BYTE) NULL ,
"TASK1" CHAR(1 BYTE) NULL 
);
COMMENT ON COLUMN "BAS_MERCHANT_CENTRE_ACCOUNT"."CUSTOMER_NO" IS '客户号';
COMMENT ON COLUMN "BAS_MERCHANT_CENTRE_ACCOUNT"."MANAGER_EMAIL" IS '商户管理员邮箱';
COMMENT ON COLUMN "BAS_MERCHANT_CENTRE_ACCOUNT"."MANAGER_TEL" IS '商户管理员绑定手机号';
COMMENT ON COLUMN "BAS_MERCHANT_CENTRE_ACCOUNT"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "BAS_MERCHANT_CENTRE_ACCOUNT"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "BAS_MERCHANT_CENTRE_ACCOUNT"."TASK1" IS '/** 向商户中心推送账号标识：0-未推送成功，1-已推送成功 */';
ALTER TABLE "BAS_MERCHANT_CENTRE_ACCOUNT" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "BAS_MERCHANT_CENTRE_ACCOUNT" ADD PRIMARY KEY ("ID");


--商户配置
CREATE SEQUENCE  "SEQ_BAS_MERCHANT_CONFIG"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 700 CACHE 20 NOORDER  NOCYCLE;
CREATE TABLE "BAS_MERCHANT_CONFIG" (
"ID" NUMBER(16) NOT NULL ,
"CUSTOMER_NO" VARCHAR2(20 BYTE) NULL ,
"SETTLEMENT_PERIOD" VARCHAR2(10 BYTE) NULL ,
"CONSUME" CHAR(1 BYTE) NULL ,
"REFUND" CHAR(1 BYTE) NULL ,
"SETTLEMENT" CHAR(1 BYTE) NULL ,
"CROSS_BORDER" CHAR(1 BYTE) NULL ,
"PAY_TYPE" VARCHAR2(150 BYTE) NULL ,
"PAY_TYPE_DIC" VARCHAR2(1000 BYTE) NULL,
"MIN_WITHDRAW_CASH_MONEY" VARCHAR2(20 BYTE) NULL ,
"PAYMENT_ACCOUNT" CHAR(1 BYTE) NULL ,
"EXCHANGE_DEPOSIT_RATE" VARCHAR2(10 BYTE) NULL ,
"PURCHASE_PAYMENT_BANK_CHANNEL" VARCHAR2(5 BYTE) NULL ,
"RECEIVE_SETT_BANK_CHANNEL" VARCHAR2(5 BYTE) NULL ,
"OPENED_CURRENCY_ACCOUNT" VARCHAR2(150 BYTE) NULL ,
"OPENED_CURRENCY_ACCOUNT_DIC" VARCHAR2(1000 BYTE) NULL ,
"CREATE_TIME" CHAR(19 BYTE) NULL ,
"UPDATE_TIME" CHAR(19 BYTE) NULL
);
ALTER TABLE "BAS_MERCHANT_CONFIG" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "BAS_MERCHANT_CONFIG" ADD PRIMARY KEY ("ID");


--商户电子资料
CREATE SEQUENCE  "SEQ_BAS_M_E_D"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE TABLE "BAS_MERCHANT_ELECTRONIC_DATA" (
"ID" NUMBER(16) NOT NULL ,
"BUSINESS_LICENSE" VARCHAR2(1000 BYTE) NULL ,
"OPEN_ACCOUNT_PERMIT" VARCHAR2(1000 BYTE) NULL ,
"CORP_ID_CARD_FRONT" VARCHAR2(1000 BYTE) NULL ,
"CORP_ID_CARD_BACK" VARCHAR2(1000 BYTE) NULL ,
"CORP_IDENTITY_CHECK" VARCHAR2(1000 BYTE) NULL ,
"CORP_HAND_ID_CARD" VARCHAR2(1000 BYTE) NULL ,
"ICP_ARCHIVAL" VARCHAR2(1000 BYTE) NULL ,
"ICP_AUTHORIZATION" VARCHAR2(1000 BYTE) NULL ,
"MOBAO_PAYMENT_AGREEMENT" VARCHAR2(1000 BYTE) NULL ,
"MOBAO_MERCHANT_REGISTRATION" VARCHAR2(1000 BYTE) NULL ,
"MOBAO_ENTRUST_AGREEMENT" VARCHAR2(1000 BYTE) NULL ,
"ENTRUST_PERSONNEL_LIST" VARCHAR2(1000 BYTE) NULL ,
"SHAREHOLDER_FUNDING" VARCHAR2(1000 BYTE) NULL ,
"BUSINESS_MODEL" VARCHAR2(1000 BYTE) NULL ,
"SPECIAL_BUSINESS_CERTIFICATE" VARCHAR2(1000 BYTE) NULL ,
"BUSINESS_INFO" VARCHAR2(1000 BYTE) NULL ,
"OFFICE_SCENE_PHOTO" VARCHAR2(1000 BYTE) NULL ,
"DOORPLATE_PHOTO" VARCHAR2(1000 BYTE) NULL ,
"WEBSITE_HOMEPAGE" VARCHAR2(1000 BYTE) NULL ,
"WEBSITE_ORDER_PAGE" VARCHAR2(1000 BYTE) NULL ,
"CUSTOMS_REGISTRATION" VARCHAR2(1000 BYTE) NULL ,
"FOREIGN_TRADE_REGISTRATION" VARCHAR2(1000 BYTE) NULL ,
"LOGISTICS_COMPACT" VARCHAR2(1000 BYTE) NULL ,
"MOBAO_OUT_CROSS_BORDER_PAYMENT" VARCHAR2(1000 BYTE) NULL ,
"MOBAO_CROSS_BORDER_PAYMENT" VARCHAR2(1000 BYTE) NULL ,
"INDIVIDUAL_IDENTITY_CHECK" VARCHAR2(1000 BYTE) NULL ,
"OVERSEAS_WEBSITE_ARCHIVAL" VARCHAR2(1000 BYTE) NULL ,
"DEPEND_PLATFORM_COMPACT" VARCHAR2(1000 BYTE) NULL ,
"CROSS_BORDER_MERCHANT_COMPACT" VARCHAR2(1000 BYTE) NULL ,
"MERCHANT_COMPACT" VARCHAR2(1000 BYTE) NULL ,
"GOVERNMENT_BUSINESS_CERTIFY" VARCHAR2(1000 BYTE) NULL ,
"CORP_IDENTITY" VARCHAR2(1000 BYTE) NULL ,
"WAREHOUSE_PHOTO" VARCHAR2(1000 BYTE) NULL ,
"STOCK_CHANNEL_CERTIFY" VARCHAR2(1000 BYTE) NULL ,
"DUE_BANK_ACCOUNT_CERTIFY" VARCHAR2(1000 BYTE) NULL ,
"OTHERS" VARCHAR2(1000 BYTE) NULL ,
"SUPPLEMENT" CLOB NULL ,
"CUSTOMER_NO" VARCHAR2(20 BYTE) NULL ,
"CREATE_TIME" CHAR(19 BYTE) NULL ,
"UPDATE_TIME" CHAR(19 BYTE) NULL 
);
COMMENT ON COLUMN "BAS_MERCHANT_ELECTRONIC_DATA"."BUSINESS_LICENSE" IS '营业执照(三证合一)';
COMMENT ON COLUMN "BAS_MERCHANT_ELECTRONIC_DATA"."OPEN_ACCOUNT_PERMIT" IS '开户许可证';
COMMENT ON COLUMN "BAS_MERCHANT_ELECTRONIC_DATA"."CORP_ID_CARD_FRONT" IS '法人身份证正面';
COMMENT ON COLUMN "BAS_MERCHANT_ELECTRONIC_DATA"."CORP_ID_CARD_BACK" IS '法人身份证反面 ';
COMMENT ON COLUMN "BAS_MERCHANT_ELECTRONIC_DATA"."CORP_IDENTITY_CHECK" IS '法人身份信息核查';
COMMENT ON COLUMN "BAS_MERCHANT_ELECTRONIC_DATA"."CORP_HAND_ID_CARD" IS '法人手持身份证';
COMMENT ON COLUMN "BAS_MERCHANT_ELECTRONIC_DATA"."ICP_ARCHIVAL" IS 'ICP备案信息 ';
COMMENT ON COLUMN "BAS_MERCHANT_ELECTRONIC_DATA"."ICP_AUTHORIZATION" IS 'ICP授权书（非自有）';
COMMENT ON COLUMN "BAS_MERCHANT_ELECTRONIC_DATA"."MOBAO_PAYMENT_AGREEMENT" IS 'Mo宝支付服务协议 ';
COMMENT ON COLUMN "BAS_MERCHANT_ELECTRONIC_DATA"."MOBAO_MERCHANT_REGISTRATION" IS 'Mo宝支付商户信息登记表 ';
COMMENT ON COLUMN "BAS_MERCHANT_ELECTRONIC_DATA"."MOBAO_ENTRUST_AGREEMENT" IS 'Mo宝支付委托结算协议';
COMMENT ON COLUMN "BAS_MERCHANT_ELECTRONIC_DATA"."ENTRUST_PERSONNEL_LIST" IS '委托结算人员名单';
COMMENT ON COLUMN "BAS_MERCHANT_ELECTRONIC_DATA"."SHAREHOLDER_FUNDING" IS '股东出资说明';
COMMENT ON COLUMN "BAS_MERCHANT_ELECTRONIC_DATA"."BUSINESS_MODEL" IS '业务模式情况说明  ';
COMMENT ON COLUMN "BAS_MERCHANT_ELECTRONIC_DATA"."SPECIAL_BUSINESS_CERTIFICATE" IS '特殊行业经营许可证明 ';
COMMENT ON COLUMN "BAS_MERCHANT_ELECTRONIC_DATA"."BUSINESS_INFO" IS '工商信息';
COMMENT ON COLUMN "BAS_MERCHANT_ELECTRONIC_DATA"."OFFICE_SCENE_PHOTO" IS '办公场景照 ';
COMMENT ON COLUMN "BAS_MERCHANT_ELECTRONIC_DATA"."DOORPLATE_PHOTO" IS '门牌照';
COMMENT ON COLUMN "BAS_MERCHANT_ELECTRONIC_DATA"."WEBSITE_HOMEPAGE" IS '网站首页';
COMMENT ON COLUMN "BAS_MERCHANT_ELECTRONIC_DATA"."WEBSITE_ORDER_PAGE" IS '网站下单页面 ';
COMMENT ON COLUMN "BAS_MERCHANT_ELECTRONIC_DATA"."CUSTOMS_REGISTRATION" IS '海关报关单位注册登记证书';
COMMENT ON COLUMN "BAS_MERCHANT_ELECTRONIC_DATA"."FOREIGN_TRADE_REGISTRATION" IS '对外贸易经营者备案登记表';
COMMENT ON COLUMN "BAS_MERCHANT_ELECTRONIC_DATA"."LOGISTICS_COMPACT" IS '与物流合作协议';
COMMENT ON COLUMN "BAS_MERCHANT_ELECTRONIC_DATA"."MOBAO_OUT_CROSS_BORDER_PAYMENT" IS 'Mo宝出口电商跨境支付协议';
COMMENT ON COLUMN "BAS_MERCHANT_ELECTRONIC_DATA"."MOBAO_CROSS_BORDER_PAYMENT" IS 'Mo宝跨境支付服务协议';
COMMENT ON COLUMN "BAS_MERCHANT_ELECTRONIC_DATA"."INDIVIDUAL_IDENTITY_CHECK" IS '个人身份信息核查';
COMMENT ON COLUMN "BAS_MERCHANT_ELECTRONIC_DATA"."OVERSEAS_WEBSITE_ARCHIVAL" IS '境外网站备案信息';
COMMENT ON COLUMN "BAS_MERCHANT_ELECTRONIC_DATA"."DEPEND_PLATFORM_COMPACT" IS '挂靠平台合作协议';
COMMENT ON COLUMN "BAS_MERCHANT_ELECTRONIC_DATA"."CROSS_BORDER_MERCHANT_COMPACT" IS '与境外商户合作协议';
COMMENT ON COLUMN "BAS_MERCHANT_ELECTRONIC_DATA"."MERCHANT_COMPACT" IS '与境内商户合作协议';
COMMENT ON COLUMN "BAS_MERCHANT_ELECTRONIC_DATA"."GOVERNMENT_BUSINESS_CERTIFY" IS '政府部门营业证明文件';
COMMENT ON COLUMN "BAS_MERCHANT_ELECTRONIC_DATA"."CORP_IDENTITY" IS '法定授权代表人身份证明文件';
COMMENT ON COLUMN "BAS_MERCHANT_ELECTRONIC_DATA"."WAREHOUSE_PHOTO" IS '仓库照';
COMMENT ON COLUMN "BAS_MERCHANT_ELECTRONIC_DATA"."STOCK_CHANNEL_CERTIFY" IS '进货渠道证明';
COMMENT ON COLUMN "BAS_MERCHANT_ELECTRONIC_DATA"."DUE_BANK_ACCOUNT_CERTIFY" IS '收款银行账户证明';
COMMENT ON COLUMN "BAS_MERCHANT_ELECTRONIC_DATA"."OTHERS" IS '其他信息';
COMMENT ON COLUMN "BAS_MERCHANT_ELECTRONIC_DATA"."CUSTOMER_NO" IS '客户号';
COMMENT ON COLUMN "BAS_MERCHANT_ELECTRONIC_DATA"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "BAS_MERCHANT_ELECTRONIC_DATA"."UPDATE_TIME" IS '更新时间';
ALTER TABLE "BAS_MERCHANT_ELECTRONIC_DATA" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "BAS_MERCHANT_ELECTRONIC_DATA" ADD PRIMARY KEY ("ID");


--商户费率
CREATE SEQUENCE  "SEQ_BAS_MERCHANT_FEE_RATE"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 8000 CACHE 20 NOORDER  NOCYCLE;
CREATE TABLE "BAS_MERCHANT_FEE_RATE" (
"ID" NUMBER(16) NOT NULL ,
"PAY_TYPE" VARCHAR2(5 BYTE) NULL ,
"BANK_CODE" VARCHAR2(20 BYTE) NULL ,
"FEE_TYPE" CHAR(1 BYTE) NULL ,
"FEE_RATE" VARCHAR2(20 BYTE) NULL ,
"MIN_FEE" VARCHAR2(20 BYTE) NULL ,
"MAX_FEE" VARCHAR2(20 BYTE) NULL ,
"START_DATE" CHAR(10 BYTE) NULL ,
"END_DATE" CHAR(10 BYTE) NULL ,
"CREATE_TIME" CHAR(19 BYTE) NULL ,
"UPDATE_TIME" CHAR(19 BYTE) NULL ,
"IF_EFFECTIVE" CHAR(1 BYTE) NULL ,
"CUSTOMER_NO" VARCHAR2(20 BYTE) NULL ,
"PRODUCT_KIND" VARCHAR2(30 BYTE) NULL ,
"FIXED_AMOUNT" VARCHAR2(20 BYTE) NULL 
);
COMMENT ON COLUMN "BAS_MERCHANT_FEE_RATE"."PAY_TYPE" IS '支付方式 （数据字典：pay_type）';
COMMENT ON COLUMN "BAS_MERCHANT_FEE_RATE"."BANK_CODE" IS '银行编码';
COMMENT ON COLUMN "BAS_MERCHANT_FEE_RATE"."FEE_TYPE" IS '计费方式 （数据字典：fee_type 1-固定值 2-按比例）';
COMMENT ON COLUMN "BAS_MERCHANT_FEE_RATE"."FEE_RATE" IS '费率 （计费方式为“按比例”时赋值）';
COMMENT ON COLUMN "BAS_MERCHANT_FEE_RATE"."MIN_FEE" IS '保底';
COMMENT ON COLUMN "BAS_MERCHANT_FEE_RATE"."MAX_FEE" IS '封顶';
COMMENT ON COLUMN "BAS_MERCHANT_FEE_RATE"."START_DATE" IS '生效日期';
COMMENT ON COLUMN "BAS_MERCHANT_FEE_RATE"."END_DATE" IS '失效日期';
COMMENT ON COLUMN "BAS_MERCHANT_FEE_RATE"."IF_EFFECTIVE" IS '产品预留，暂未使用';
COMMENT ON COLUMN "BAS_MERCHANT_FEE_RATE"."CUSTOMER_NO" IS '客户号';
COMMENT ON COLUMN "BAS_MERCHANT_FEE_RATE"."PRODUCT_KIND" IS '产品类型 （数据字典：product_kind）';
COMMENT ON COLUMN "BAS_MERCHANT_FEE_RATE"."FIXED_AMOUNT" IS '固定金额 （计费方式为“固定值”时赋值）';
ALTER TABLE "BAS_MERCHANT_FEE_RATE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "BAS_MERCHANT_FEE_RATE" ADD PRIMARY KEY ("ID");


--商户即时结算
CREATE SEQUENCE  "SEQ_B_M_FUND_SETTLEMENT"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 100 CACHE 20 NOORDER  NOCYCLE;
CREATE TABLE "BAS_MERCHANT_FUND_SETTLEMENT" (
"ID" NUMBER(16) NOT NULL ,
"CUSTOMER_NO" VARCHAR2(20 BYTE) NULL ,
"OPEN_FUND_SETTLEMENT" VARCHAR2(30 BYTE) NULL ,
"FEE_TYPE" CHAR(1 BYTE) NULL ,
"FEE_RATE" VARCHAR2(20 BYTE) NULL ,
"FIXED_AMOUNT" VARCHAR2(20 BYTE) NULL ,
"SINGLE_DAY_MAX_FUND" VARCHAR2(20 BYTE) NULL ,
"FUND_SETTLEMENT_SCALE" VARCHAR2(20 BYTE) NULL ,
"CREATE_TIME" CHAR(19 BYTE) NULL ,
"UPDATE_TIME" CHAR(19 BYTE) NULL ,
"CUSTOMER_NAME" VARCHAR2(100 BYTE) NULL 
);
COMMENT ON COLUMN "BAS_MERCHANT_FUND_SETTLEMENT"."CUSTOMER_NO" IS '客户号';
COMMENT ON COLUMN "BAS_MERCHANT_FUND_SETTLEMENT"."OPEN_FUND_SETTLEMENT" IS '开通垫资结算 (1-T0  2-D0   0-关闭)';
COMMENT ON COLUMN "BAS_MERCHANT_FUND_SETTLEMENT"."FEE_TYPE" IS '计费方式 （数据字典：fee_type 1-固定值 2-按比例）';
COMMENT ON COLUMN "BAS_MERCHANT_FUND_SETTLEMENT"."FEE_RATE" IS '费率 （计费方式为“按比例”时赋值）';
COMMENT ON COLUMN "BAS_MERCHANT_FUND_SETTLEMENT"."FIXED_AMOUNT" IS '固定金额 （计费方式为“固定值”时赋值）';
COMMENT ON COLUMN "BAS_MERCHANT_FUND_SETTLEMENT"."SINGLE_DAY_MAX_FUND" IS '单日最高垫资金额';
COMMENT ON COLUMN "BAS_MERCHANT_FUND_SETTLEMENT"."FUND_SETTLEMENT_SCALE" IS '垫资结算比例';
COMMENT ON COLUMN "BAS_MERCHANT_FUND_SETTLEMENT"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "BAS_MERCHANT_FUND_SETTLEMENT"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "BAS_MERCHANT_FUND_SETTLEMENT"."CUSTOMER_NAME" IS '商户全称';
ALTER TABLE "BAS_MERCHANT_FUND_SETTLEMENT" ADD PRIMARY KEY ("ID");


--商户基本信息
CREATE SEQUENCE  "SEQ_BAS_MERCHANT_INFO"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 100 CACHE 20 NOORDER  NOCYCLE;
CREATE TABLE "BAS_MERCHANT_INFO" (
"ID" NUMBER(16) NOT NULL ,
"CUSTOMER_NO" VARCHAR2(20 BYTE) NULL ,
"OLD_CUSTOMER_NO" CHAR(16 BYTE) NULL ,
"PLATFORM_CUSTOMER_NO" VARCHAR2(20 BYTE) NULL ,
"SHORT_NAME" VARCHAR2(70 BYTE) NULL ,
"NAME" VARCHAR2(70 BYTE) NULL ,
"STATUS" CHAR(1 BYTE) NULL ,
"SHAREHOLDER" VARCHAR2(100 BYTE) NULL ,
"SHAREHOLDER_ID_NUM" VARCHAR2(50 BYTE) NULL ,
"LEGAL_PERSON" VARCHAR2(40 BYTE) NULL ,
"LEGAL_PERSON_CERT_TYPE" CHAR(1 BYTE) NULL ,
"LEGAL_PERSON_CERT_NUM" VARCHAR2(50 BYTE) NULL ,
"LEGAL_PERSON_CERT_PERIOD_START" CHAR(10 BYTE) NULL ,
"LEGAL_PERSON_SEX" CHAR(1 BYTE) NULL ,
"LEGAL_PERSON_CAREER" VARCHAR2(20 BYTE) NULL ,
"LEGAL_PERSON_NATIONALITY" VARCHAR2(10 BYTE) NULL ,
"BUSINESS_LICENCE_NO" VARCHAR2(100 BYTE) NULL ,
"BUSINESS_LICENCE_PERIOD_START" CHAR(10 BYTE) NULL ,
"REGISTERED_FUND" VARCHAR2(20 BYTE) NULL ,
"BUSINESS_SCOPE" VARCHAR2(3000 BYTE) NULL ,
"CONTACT_PERSON" VARCHAR2(30 BYTE) NULL ,
"CONTACT_PHONE" VARCHAR2(20 BYTE) NULL ,
"ADDRESS" VARCHAR2(400 BYTE) NULL ,
"ECOMMERCE_DOMAIN" VARCHAR2(30 BYTE) NULL ,
"ICP" VARCHAR2(100 BYTE) NULL ,
"ICP_PERIOD_START" CHAR(10 BYTE) NULL ,
"INDUSTRY_CODE" VARCHAR2(5 BYTE) NULL ,
"AREA_CODE" VARCHAR2(5 BYTE) NULL ,
"SALESMAN_NO" CHAR(4 BYTE) NULL ,
"SALESMAN_NAME" VARCHAR2(10 BYTE) NULL ,
"AGENT_NO" VARCHAR2(20 BYTE) NULL ,
"AGENT_NAME" VARCHAR2(30 BYTE) NULL ,
"MERCHANT_TYPE" CHAR(1 BYTE) NULL ,
"STAFF" VARCHAR2(30 BYTE) NULL ,
"STAFF_CERT_TYPE" CHAR(1 BYTE) NULL ,
"STAFF_CERT_NUM" VARCHAR2(100 BYTE) NULL ,
"STAFF_CERT_PERIOD_START" CHAR(10 BYTE) NULL ,
"IF_SUBMIT_CUSTOMS" CHAR(1 BYTE) NULL ,
"CUSTOMS" CHAR(1 BYTE) NULL ,
"CUSTOMS_REGISTER_NO" VARCHAR2(30 BYTE) NULL ,
"EXIT_BUSINESS_MODEL" CHAR(1 BYTE) NULL ,
"ECOMMERCE_WEBSITE_NAME" VARCHAR2(50 BYTE) NULL ,
"CREATE_TIME" CHAR(19 BYTE) NULL ,
"UPDATE_TIME" CHAR(19 BYTE) NULL ,
"LOCK_TIME" CHAR(19 BYTE) NULL ,
"CANCEL_TIME" CHAR(19 BYTE) NULL ,
"BRANCH_NO" CHAR(3 BYTE) NULL ,
"MERCHANT_ATTRIBUTE" CHAR(1 BYTE) NULL ,
"MERCHANT_PROPERTY" CHAR(1 BYTE) NULL ,
"LEGAL_PERSON_CERT_PERIOD_END" CHAR(10 BYTE) NULL ,
"BUSINESS_LICENCE_PERIOD_END" CHAR(10 BYTE) NULL ,
"MERCHANT_DOMAIN" VARCHAR2(200 BYTE) NULL ,
"ICP_PERIOD_END" CHAR(10 BYTE) NULL ,
"STAFF_CERT_PERIOD_END" CHAR(10 BYTE) NULL ,
"CROSS_BORDER_ENTRANCE" VARCHAR2(20 BYTE) NULL ,
"INDUSTRY_NAME" VARCHAR2(100 BYTE) NULL ,
"BUSINESS_KIND" CHAR(1 BYTE) NULL ,
"BUSINESS_TYPE" VARCHAR2(20 BYTE) NULL ,
"MCC_CODE" VARCHAR2(10 BYTE) NULL ,
"MCC_KIND_NAME" VARCHAR2(100 BYTE) NULL ,
"WECHAT_BUSINESS_KIND_CODE" VARCHAR2(10 BYTE) NULL ,
"WECHAT_BUSINESS_KIND_NAME" VARCHAR2(100 BYTE) NULL ,
"NUCC_BUSINESS_KIND_CODE" VARCHAR2(10 BYTE) NULL ,
"NUCC_BUSINESS_KIND_NAME" VARCHAR2(100 BYTE) NULL ,
"ALIPAY_BUSINESS_KIND" VARCHAR2(20 BYTE) NULL ,
"CONTACT_CERT_NUM" VARCHAR2(50 BYTE) NULL ,
"CONTACT_ID_PERIOD_START" CHAR(10 BYTE) NULL ,
"CONTACT_ID_PERIOD_END" CHAR(10 BYTE) NULL ,
"CONTACT_EMAIL" VARCHAR2(30 BYTE) NULL ,
"CUSTOMER_TEL" VARCHAR2(20 BYTE) NULL ,
"BUSINESS_TYPE_DIC" VARCHAR2(255 BYTE) NULL ,
"TASK1" CHAR(1 BYTE) NULL ,
"RISK_TASK" CHAR(1 BYTE) NULL ,
"TRADE_CHECK" CHAR(1 BYTE) NULL ,
"LAST_TRADE_DATE" CHAR(10 BYTE) NULL ,
"LAST_OUT_DATE" CHAR(10 BYTE) NULL ,
"CUP_BUSINESS_KIND" VARCHAR2(10 BYTE) NULL
);
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."CUSTOMER_NO" IS '客户号';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."OLD_CUSTOMER_NO" IS '老客户号(对应老系统迁移数据的客户号)';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."SHORT_NAME" IS '商户简称';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."NAME" IS '商户全称';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."STATUS" IS '商户状态（数据字典 merchant_status：1-活动 2-锁定 3-注销）';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."SHAREHOLDER" IS '控股股东或实际控制人';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."SHAREHOLDER_ID_NUM" IS '股东身份证号';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."LEGAL_PERSON" IS '法人代表';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."LEGAL_PERSON_CERT_TYPE" IS '法人证件类型（数据字典 certificate_type：0-身份证 1-护照）';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."LEGAL_PERSON_CERT_NUM" IS '法人证件编号';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."LEGAL_PERSON_CERT_PERIOD_START" IS '法人证件有效期开始时间';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."LEGAL_PERSON_SEX" IS '法人性别（数据字典 sex：0-男 1-女）';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."LEGAL_PERSON_CAREER" IS '法人职业（数据字典 occupation）';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."LEGAL_PERSON_NATIONALITY" IS '法人国籍（数据字典 nationality）';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."BUSINESS_LICENCE_NO" IS '营业执照号';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."BUSINESS_LICENCE_PERIOD_START" IS '营业执照有效期开始时间';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."REGISTERED_FUND" IS '注册资金';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."BUSINESS_SCOPE" IS '经营范围';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."CONTACT_PERSON" IS '联系人';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."CONTACT_PHONE" IS '联系电话';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."ADDRESS" IS '商户地址';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."ECOMMERCE_DOMAIN" IS '备案域名/电商网站域名';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."ICP" IS 'ICP备案号';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."ICP_PERIOD_START" IS 'ICP备案有效时间开始时间';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."INDUSTRY_CODE" IS '所属行业（关联"行业信息"模块IndustryInfo）';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."AREA_CODE" IS '所属地区(数据字典 area_code)';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."SALESMAN_NO" IS '所属销售（关联销售信息）';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."SALESMAN_NAME" IS '所属销售姓名（冗余设计）';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."AGENT_NO" IS '所属代理 （关联代理信息）';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."AGENT_NAME" IS '所属代理名称 （冗余设计）';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."MERCHANT_TYPE" IS '商户类型(数据字典 merchant_type：1-个人，2-企业)';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."STAFF" IS '授权办理业务人员的姓名';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."STAFF_CERT_TYPE" IS '授权办理业务人员证件类型（数据字典 certificate_type：0-身份证 1-护照）';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."STAFF_CERT_NUM" IS '授权办理业务人员证件号';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."STAFF_CERT_PERIOD_START" IS '授权办理业务人员证件有效期开始时间';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."IF_SUBMIT_CUSTOMS" IS '是否报送海关：0-报送，1-不报送';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."CUSTOMS" IS '报送海关（数据字典 default_customs：0-四川 1-成都）';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."CUSTOMS_REGISTER_NO" IS '海关登记编号';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."EXIT_BUSINESS_MODEL" IS '出口业务模式（数据字典 exit_business_model：1-企业自建站，2-挂靠电商平台';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."ECOMMERCE_WEBSITE_NAME" IS '电商网站名称';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."LOCK_TIME" IS '锁定时间';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."CANCEL_TIME" IS '注销时间';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."BRANCH_NO" IS '分支机构号';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."MERCHANT_ATTRIBUTE" IS '商户属性（数据字典 merchant_attribute 1-直营商户 2-代理商户）';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."LEGAL_PERSON_CERT_PERIOD_END" IS '法人证件有效期结束时间';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."BUSINESS_LICENCE_PERIOD_END" IS '营业执照有效期结束时间';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."MERCHANT_DOMAIN" IS '商户域名';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."ICP_PERIOD_END" IS 'ICP备案有效日期结束时间';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."STAFF_CERT_PERIOD_END" IS '授权办理业务人员证件有效期结束时间';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."CROSS_BORDER_ENTRANCE" IS '跨境进口商户属性';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."INDUSTRY_NAME" IS '所属行业名称';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."BUSINESS_KIND" IS '业务种类（数据字典 business_kind：1-互联网，2-移动支付）';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."BUSINESS_TYPE" IS '业务类型(数据字典 merchant_business_type：1-普通业务，2-跨境进口，3-跨境出口，4-跨境通关)';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."MCC_CODE" IS 'MCC代码（关联MCC表）';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."MCC_KIND_NAME" IS 'MCC类目名称（冗余设计）';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."WECHAT_BUSINESS_KIND_CODE" IS '微信经营类目代码（关联微信经营类目表）';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."WECHAT_BUSINESS_KIND_NAME" IS '微信经营类目名称（冗余设计）';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."NUCC_BUSINESS_KIND_CODE" IS '网联业务种类代码（关联网联业务种类表）';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."NUCC_BUSINESS_KIND_NAME" IS '网联业务种类名称';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."ALIPAY_BUSINESS_KIND" IS '支付宝经营类目（数据字典 alipay_business_kind）';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."CONTACT_CERT_NUM" IS '联系人身份证号码';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."CONTACT_ID_PERIOD_START" IS '联系人身份证有效期开始时间';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."CONTACT_ID_PERIOD_END" IS '联系人身份证有效期结束时间';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."CONTACT_EMAIL" IS '联系人邮箱';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."CUSTOMER_TEL" IS '客服电话';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."BUSINESS_TYPE_DIC" IS '业务类型(中文名称)';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."TASK1" IS '向交易服务推送开户数据：0-未推送成功，1-已推送成功';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."TRADE_CHECK" IS '交易是否需要被检查：0-否，1-是';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."LAST_TRADE_DATE" IS '最后交易日期：由订单系统每天推送';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."CUP_BUSINESS_KIND" IS '银联业务种类';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."LAST_OUT_DATE" IS '最后出款日期：由订单系统每天推送';
COMMENT ON COLUMN "BAS_MERCHANT_INFO"."RISK_TASK" IS '向风控系统推送新入网的客户号：0-未推送成功，1-已推送成功';
ALTER TABLE "BAS_MERCHANT_INFO" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "BAS_MERCHANT_INFO" ADD PRIMARY KEY ("ID");


--商户结算信息
CREATE SEQUENCE  "SEQ_BAS_SETTLEMENT_INFO"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 300 CACHE 20 NOORDER  NOCYCLE;
CREATE TABLE "BAS_MERCHANT_SETTLEMENT_INFO" (
"ID" NUMBER(16) NOT NULL ,
"CUSTOMER_NO" VARCHAR2(20 BYTE) NULL ,
"BANK_ACCOUNT_NAME" VARCHAR2(100 BYTE) NULL ,
"PAYEE_ID_NUM" VARCHAR2(50 BYTE) NULL ,
"ACCOUNT_NO" VARCHAR2(50 BYTE) NULL ,
"RESERVE_MOBILE_NO" VARCHAR2(50 BYTE) NULL ,
"BANK_NO" VARCHAR2(20 BYTE) NULL ,
"BANK_NAME" VARCHAR2(90 BYTE) NULL ,
"ACCOUNT_TYPE" CHAR(1 BYTE) NULL ,
"BRANCH_BANK_NO" VARCHAR2(15 BYTE) NULL ,
"BRANCH_BANK_NAME" VARCHAR2(90 BYTE) NULL ,
"CREATE_TIME" CHAR(19 BYTE) NULL ,
"UPDATE_TIME" CHAR(19 BYTE) NULL ,
"PROVINCE" VARCHAR2(100 BYTE) NULL ,
"PROVINCE_CODE" VARCHAR2(5 BYTE) NULL ,
"CITY" VARCHAR2(100 BYTE) NULL ,
"CITY_CODE" VARCHAR2(5 BYTE) NULL 
);
COMMENT ON TABLE "BAS_MERCHANT_SETTLEMENT_INFO" IS '商户结算信息';
COMMENT ON COLUMN "BAS_MERCHANT_SETTLEMENT_INFO"."CUSTOMER_NO" IS '客户号（商户1开头，个人5开头）';
COMMENT ON COLUMN "BAS_MERCHANT_SETTLEMENT_INFO"."BANK_ACCOUNT_NAME" IS '开户户名';
COMMENT ON COLUMN "BAS_MERCHANT_SETTLEMENT_INFO"."PAYEE_ID_NUM" IS '收款人身份证号';
COMMENT ON COLUMN "BAS_MERCHANT_SETTLEMENT_INFO"."ACCOUNT_NO" IS '开户账号';
COMMENT ON COLUMN "BAS_MERCHANT_SETTLEMENT_INFO"."RESERVE_MOBILE_NO" IS '银行预留手机号';
COMMENT ON COLUMN "BAS_MERCHANT_SETTLEMENT_INFO"."BANK_NO" IS '开户行行号';
COMMENT ON COLUMN "BAS_MERCHANT_SETTLEMENT_INFO"."BANK_NAME" IS '开户行名称';
COMMENT ON COLUMN "BAS_MERCHANT_SETTLEMENT_INFO"."ACCOUNT_TYPE" IS '账户类型（1：对私 2：对公）';
COMMENT ON COLUMN "BAS_MERCHANT_SETTLEMENT_INFO"."BRANCH_BANK_NO" IS '分支行行号';
COMMENT ON COLUMN "BAS_MERCHANT_SETTLEMENT_INFO"."BRANCH_BANK_NAME" IS '分支行名称';
COMMENT ON COLUMN "BAS_MERCHANT_SETTLEMENT_INFO"."PROVINCE" IS '省名称';
COMMENT ON COLUMN "BAS_MERCHANT_SETTLEMENT_INFO"."PROVINCE_CODE" IS '省代码';
COMMENT ON COLUMN "BAS_MERCHANT_SETTLEMENT_INFO"."CITY" IS '市名称';
COMMENT ON COLUMN "BAS_MERCHANT_SETTLEMENT_INFO"."CITY_CODE" IS '市代码';
ALTER TABLE "BAS_MERCHANT_SETTLEMENT_INFO" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "BAS_MERCHANT_SETTLEMENT_INFO" ADD PRIMARY KEY ("ID");


--销售信息
CREATE SEQUENCE  "SEQ_BAS_SALESMAN"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE TABLE "BAS_SALESMAN" (
"ID" NUMBER(16) NOT NULL ,
"SALES_NO" CHAR(4 BYTE) NULL ,
"NAME" VARCHAR2(30 BYTE) NULL ,
"EMAIL" VARCHAR2(30 BYTE) NULL ,
"TEL" VARCHAR2(20 BYTE) NULL 
);
ALTER TABLE "BAS_SALESMAN" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "BAS_SALESMAN" ADD PRIMARY KEY ("ID");
